/*
 * A PORT OF `engines/pump/crates/pump-core/src/shape.rs`, AND THE ONLY COPY IN
 * THE UI.
 *
 * Plain JavaScript with no JSX and no imports, on purpose: this is the one
 * piece of the editor that must agree with the DSP to the digit, so it has to
 * be loadable by `node --test` without a build step. It lives in its own file
 * for the same reason -- inside a component nothing could reach it, which is
 * how the Trance Gate's S-curve stayed wrong for as long as it did.
 *
 * NEITHER COPY IS COMPARED AGAINST THE OTHER. Both this and the C are pinned
 * to `test/shape_table.txt`, generated by the engine itself. Two identically
 * wrong transcriptions agree with each other perfectly; only the engine's own
 * output settles it. A picture that merely looks plausible is not evidence.
 *
 * Regenerate the fixture with `pump_shape_table`, and only when the curve maths
 * is MEANT to change.
 */

/* The bend, and the divisor. `DENOM` is `1 - exp(-3)` SPELLED OUT, exactly as
 * the Rust and the C spell it, so the division is the same division. Writing
 * it as `1 - Math.exp(-K)` would be a different number in the last place, and
 * the fixture is compared at 1e-12. */
const K = 3.0;
const DENOM = 0.95021293163213605;

const curveExp = (t) => (1 - Math.exp(-K * t)) / DENOM;

const curveExpInv = (w) => {
  const x = 1 - w * DENOM;
  return x <= 1e-12 ? 1 : -Math.log(x) / K;
};

/** 0 Linear, 1 Exponential, 2 S-Curve, 3 Pump -- `Curve::LABELS`' order. */
export const CURVES = ['Linear', 'Exponential', 'S-Curve', 'Pump'];

/** 0 = the duck deepening, 1 = the recovery. */
export const DOWN = 0;
export const UP = 1;

/*
 * THE SHAPE IS A WARP ON TIME: every stage is f(t) with t running 0..1 across
 * it, so a curve is not a new set of formulas but one function substituted in.
 * shape(0) = 0, shape(1) = 1, monotonic -- a stage starts and ends where it did
 * and takes the time it was given; only the path between changes.
 *
 * WHY `dir` EXISTS. Three curves ignore it. `Pump` does not: it is linear going
 * down and a cubic ease-out coming back up, and that asymmetry is the whole
 * character of the curve. The invariant above still holds, independently for
 * each direction.
 */
export function shape(curve, t, dir) {
  /* `!(t > 0)` rather than `t <= 0` so a NaN lands here rather than falling
   * through to the `t >= 1` test and returning 1 -- the engine's guard. */
  if (!(t > 0)) return 0;
  if (t >= 1) return 1;
  switch (curve) {
    case 1:
      return curveExp(t);
    /*
     * TWO EXPONENTIALS, JOINED -- and the first one is MIRRORED.
     *
     * `0.5 * curveExp(2t)` on both halves is the version that was wrong in the
     * Trance Gate for as long as it was: slope K/DENOM ~ 3.16 at t=0, so the
     * curve leaves the floor vertically and hits the ceiling vertically, which
     * is the opposite of what an S-curve does at both ends.
     *
     * Reversed, the first half is slow-then-accelerating and the pair is
     * slow-fast-slow, meeting in the middle at the same slope -- Einv'(1) is
     * E'(0). A corner there would be a kink in the gain, audible as surely as
     * a step, which is why the join is not simply two arcs.
     */
    case 2:
      return t < 0.5
        ? 0.5 * (1 - curveExp(1 - 2 * t))
        : 0.5 + 0.5 * curveExp(2 * t - 1);
    /* ducker.c:137-151, via shape.rs. Linear down so the duck lands on the
     * beat with no softening; cubic ease-out up so the recovery breathes. */
    case 3: {
      if (dir === DOWN) return t;
      const inv = 1 - t;
      return 1 - inv * inv * inv;
    }
    default:
      return t;
  }
}

/** The inverse. Monotonic and analytic for all four, which is what lets the
 * curve change mid-duck without a click -- see `set_curve` in params.rs. */
export function shapeInv(curve, w, dir) {
  if (!(w > 0)) return 0;
  if (w >= 1) return 1;
  switch (curve) {
    case 1:
      return curveExpInv(w);
    case 2:
      return w < 0.5
        ? 0.5 * (1 - curveExpInv(1 - 2 * w))
        : 0.5 + 0.5 * curveExpInv(2 * w - 1);
    case 3:
      /* w = 1 - (1-t)^3  =>  t = 1 - cbrt(1-w) */
      return dir === DOWN ? w : 1 - Math.cbrt(1 - w);
    default:
      return w;
  }
}

/*
 * THE IDEALISED SINGLE SHOT, WHICH IS WHAT THE EDITOR DRAWS.
 *
 * `duckAt` is the shape one trigger makes when nothing interrupts it: from
 * zero, down to full, and back. That is the right thing for the editor,
 * because the editor is where you say what shape you WANT.
 *
 * IT IS NOT THE ENVELOPE THE ENGINE RUNS, and the difference is deliberate
 * rather than a simplification. The engine anchors a retrigger on the level it
 * has actually reached, so a duck that fires again mid-recovery does not
 * retrace this curve -- and no editor drawing can show that, because it depends
 * on when the next trigger arrives. What the plugin pushes instead is the
 * measured gain-reduction trace, drawn under the audio. The editor says the
 * intent; the trace says what happened.
 *
 * `p` carries the four stage lengths as PERCENTAGES OF THE CYCLE, the unit the
 * engine stores them in, and `t` is in the same unit. Depth is not applied:
 * this returns the attenuation 0..1, and what a given depth does with it is
 * one multiply that belongs where the drawing happens.
 */
export function duckAt(p, t) {
  const d = Math.max(0, p.delay ?? 0);
  const a = Math.max(0, p.attack ?? 0);
  const h = Math.max(0, p.hold ?? 0);
  const r = Math.max(0, p.release ?? 0);
  const curve = p.curve | 0;

  /* `t < d` and not `!(t > d)`: with no delay and no attack the engine has
   * already reached the floor by the trigger sample, so t=0 must fall THROUGH
   * this test rather than be caught by it. A NaN fails every comparison below
   * and falls out of the last `return 0`, which is the same guard by a
   * different route. */
  if (t < d) return 0;
  if (t < d + a) return shape(curve, (t - d) / a, DOWN);
  if (t < d + a + h) return 1;
  if (t < d + a + h + r) return 1 - shape(curve, (t - d - a - h) / r, UP);
  return 0;
}

/** Where each stage boundary sits, in percent of the cycle. The editor's
 * handles are these, and the axis' landmarks are these, so there is one
 * arithmetic for both. */
export function bounds(p) {
  const d = Math.max(0, p.delay ?? 0);
  const a = Math.max(0, p.attack ?? 0);
  const h = Math.max(0, p.hold ?? 0);
  const r = Math.max(0, p.release ?? 0);
  return { start: d, bottom: d + a, holdEnd: d + a + h, end: d + a + h + r };
}
