/*
 * Generates the curve fixture that BOTH copies of the shape maths are pinned
 * to -- the C one here and the JavaScript one in plugins/pump/ui/src/lib.
 *
 * THE FIXTURE IS GENERATED BY THE ENGINE, AND NEITHER COPY IS COMPARED
 * AGAINST THE OTHER. That is the whole design: comparing them to each other
 * proves only that they agree, which two identically-wrong transcriptions also
 * do. Pinning each to the engine's own output proves they agree WITH THE THING
 * THAT MAKES THE SOUND.
 *
 * Regenerate with
 *
 *     ./build/engines/pump/pump_shape_table > plugins/pump/ui/test/shape_table.txt
 *
 * and ONLY when the curve maths is meant to change. A regenerated fixture that
 * nobody intended is a test that has stopped testing.
 *
 * Format: one row per sample, "curve dir t value inverse", space separated,
 * with t at 1/1000 steps. The inverse is included so a JS port cannot pass by
 * implementing only the forward direction.
 */

#include <stdio.h>
#include "pump_core.h"

#define STEPS 1000

int main(void)
{
    printf("# curve dir t shape inverse\n");
    printf("# curves: 0 Linear, 1 Exponential, 2 S-Curve, 3 Pump\n");
    printf("# dir: 0 down (the duck deepening), 1 up (the recovery)\n");
    for (int curve = 0; curve < 4; curve++) {
        for (int dir = 0; dir < 2; dir++) {
            for (int i = 0; i <= STEPS; i++) {
                const double t = (double)i / (double)STEPS;
                /* %.17g is the shortest decimal that round-trips a double
                 * exactly, so the fixture cannot quantise what it is pinning. */
                printf("%d %d %.17g %.17g %.17g\n", curve, dir, t,
                       pump_test_shape(curve, t, dir),
                       pump_test_shape_inv(curve, t, dir));
            }
        }
    }
    return 0;
}
