// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Torben Gräber

/*
 * The kit's curve (ui-kit/src/lib/curve.js), against the Trance Gate engine's
 * own table.
 *
 * The one JavaScript copy of the envelope shape, shared with Side-Chain's
 * shaper. The fixture is generated by the engine itself (tests/shape_table.c,
 * via tg_test_shape), and both sides are checked against it rather than
 * against each other -- as Side-Chain's shape.test.mjs checks the same module
 * against its engine's table.
 *
 * node's own test runner, so the UI keeps a single dependency tree of vite and
 * solid and nothing else -- the licence audit is the whole point of that.
 *
 *   node --test ui/test/
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { shape } from '../../../../ui-kit/src/lib/curve.js';

const here = dirname(fileURLToPath(import.meta.url));
const TABLE = process.env.TG_SHAPE_TABLE ?? join(here, 'shape_table.txt');

/* Both sides use f64 exp/log but not the same libm, so an ulp of slack --
 * see the matching TOL in shape_table.c. */
const TOL = 1e-12;
const NAMES = ['linear', 'exponential', 's-curve'];

const rows = readFileSync(TABLE, 'utf8').trim().split('\n').map((l) => {
  const [c, t, w, v] = l.split(' ');
  return { c: +c, t: +t, w: +w, v: +v };
});

test('the fixture is the shape it claims to be', () => {
  assert.equal(rows.length, 3 * 1001, 'three curves, 1001 samples each');
  assert.ok(rows.every((r) => Number.isFinite(r.w) && Number.isFinite(r.v)));
});

for (const curve of [0, 1, 2]) {
  test(`shape(${NAMES[curve]}) matches the engine`, () => {
    let worst = 0, at = 0;
    for (const r of rows) {
      if (r.c !== curve) continue;
      const got = shape(curve, r.t);
      const err = Math.abs(got - r.w);
      if (err > worst) { worst = err; at = r.t; }
    }
    assert.ok(worst <= TOL,
      `worst error ${worst.toExponential(3)} at t=${at} (tolerance ${TOL})`);
  });

}

/*
 * The properties the engine's own doc comment states, checked directly. These
 * would have caught the S-curve bug on their own: the un-mirrored first half
 * left shape(0.001) at 0.003 instead of 0.00003, so it was never flat at the
 * start and never symmetric about the middle.
 */
test('every curve starts at 0, ends at 1, and is monotonic', () => {
  for (const c of [0, 1, 2]) {
    assert.equal(shape(c, 0), 0, `${NAMES[c]} at 0`);
    assert.equal(shape(c, 1), 1, `${NAMES[c]} at 1`);
    let prev = -Infinity;
    for (let i = 0; i <= 1000; i++) {
      const v = shape(c, i / 1000);
      assert.ok(v >= prev, `${NAMES[c]} fell at t=${i / 1000}`);
      prev = v;
    }
  }
});

test('the s-curve is flat at both ends and steep in the middle', () => {
  const slope = (t) => (shape(2, t + 1e-6) - shape(2, t)) / 1e-6;
  const ends = Math.max(slope(0), slope(1 - 1e-6));
  const middle = slope(0.5);
  /* This is the assertion the reported fault maps onto: "starts and ends
   * vertical instead of horizontal". The exponential's slope at 0 is
   * K/DENOM ~ 3.16, so the broken S-curve scored 3.16 here. */
  assert.ok(ends < 0.5, `ends are not flat: slope ${ends.toFixed(3)}`);
  assert.ok(middle > 1.5, `middle is not steep: slope ${middle.toFixed(3)}`);
  assert.ok(middle > ends * 4, 'an S-curve is steeper in the middle than at its ends');
});

test('the s-curve is antisymmetric about its midpoint', () => {
  assert.ok(Math.abs(shape(2, 0.5) - 0.5) < 1e-15);
  for (let i = 1; i < 500; i++) {
    const t = i / 1000;
    assert.ok(Math.abs(shape(2, t) + shape(2, 1 - t) - 1) < 1e-12,
      `shape(t) + shape(1-t) != 1 at t=${t}`);
  }
});

test('the exponential rises fast and eases in, ~82% at the halfway point', () => {
  /* The engine's own words for why K is 3. */
  assert.ok(Math.abs(shape(1, 0.5) - 0.8176) < 0.001);
});
