// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Torben Gräber

/*
 * THE TWO PATHS, RENDERED SIDE BY SIDE, AND THE RESULT PINNED.
 *
 * AGENTS.md asks that every DSP exist on both the Live plugin and the Move
 * module. This is that requirement made checkable, and it makes two separate
 * claims:
 *
 *   A/B      the plugin's path (float, split channels, a transport struct the
 *            way a DAW supplies it) and the Move's path (int16 interleaved at
 *            44100) produce the same gain, sample for sample, within the one
 *            LSB that int16 quantisation costs.
 *
 *   GOLDEN   the float render hashes to a recorded value, so a change to the
 *            shared DSP -- which by definition moves BOTH paths together and
 *            therefore passes the A/B -- still has to be deliberate.
 *
 * The A/B alone would be satisfied by an engine that broke identically in both
 * directions. The hash alone would not notice a shell that fed one path a
 * different transport. Both, and neither is redundant.
 *
 * The reference is generated by this file at a fixed input and fixed settings;
 * `--dump` prints the hash to re-record with, and only when the sound is MEANT
 * to change.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include <stdint.h>
#include "sc_core.h"
/* The patch's length, the input and the golden hash, shared with the test
 * that renders the same through the built VST3 (tests/side-chain/sc_host). */
#include "render_golden.h"

#define SR      SC_RENDER_SR
#define BLOCK   SC_RENDER_BLOCK
#define FRAMES  SC_RENDER_FRAMES
#define GOLDEN  SC_RENDER_GOLDEN

static uint64_t fnv1a(const void *p, size_t n)
{
    return sc_render_fnv1a(SC_RENDER_FNV_START, p, n);
}

static void make_input(float *l, float *r, int frames)
{
    sc_render_input(l, r, frames);
}

/* render_golden.h's SC_RENDER_PARAMS, through the engine's string door. */
static void configure(sc_core_t *c)
{
    sc_core_set_num(c, SC_P_SOURCE, 0);
    sc_core_set_param(c, "rate", "1/4");
    sc_core_set_num(c, SC_P_CURVE, 1);      /* Exponential */
    sc_core_set_num(c, SC_P_DELAY, 3.0);
    sc_core_set_num(c, SC_P_ATTACK, 6.0);
    sc_core_set_num(c, SC_P_HOLD, 11.0);
    sc_core_set_num(c, SC_P_RELEASE, 42.0);
    sc_core_set_num(c, SC_P_DEPTH, 0.85);
}

int main(int argc, char **argv)
{
    const int dump = (argc > 1 && strcmp(argv[1], "--dump") == 0);

    static float in_l[FRAMES], in_r[FRAMES];
    static float pl[FRAMES], pr[FRAMES];
    static int16_t mv[FRAMES * 2];
    make_input(in_l, in_r, FRAMES);

    /* ---- the plugin's path: float, split, a transport struct per block ---- */
    sc_core_t *plug = sc_core_create(SR);
    configure(plug);
    memcpy(pl, in_l, sizeof pl);
    memcpy(pr, in_r, sizeof pr);

    for (int off = 0; off < FRAMES; off += BLOCK) {
        const int n = (FRAMES - off < BLOCK) ? FRAMES - off : BLOCK;
        sc_transport_t t;
        t.running = 1;
        t.bpm = 120.0f;
        /* 120 bpm is two beats a second. */
        t.beats = (double)off / SR * 2.0;
        sc_core_process_f32_split(plug, pl + off, pr + off, n, &t);
    }
    sc_core_destroy(plug);

    /* ---- the Move's path: int16 interleaved, same transport ---- */
    sc_core_t *move = sc_core_create(SR);
    configure(move);
    for (int i = 0; i < FRAMES; i++) {
        /* 16384 rather than 32767: the input peaks near 0.6 and this leaves
         * the conversion well clear of the clamp, so the comparison below is
         * about the GAIN and not about saturation. */
        mv[i * 2]     = (int16_t)lrintf(in_l[i] * 16384.0f);
        mv[i * 2 + 1] = (int16_t)lrintf(in_r[i] * 16384.0f);
    }
    for (int off = 0; off < FRAMES; off += BLOCK) {
        const int n = (FRAMES - off < BLOCK) ? FRAMES - off : BLOCK;
        sc_transport_t t;
        t.running = 1;
        t.bpm = 120.0f;
        t.beats = (double)off / SR * 2.0;
        sc_core_process_i16(move, mv + off * 2, n, &t);
    }
    sc_core_destroy(move);

    /* ---------------------------------------------------------- the A/B ---- */
    int worst_at = -1;
    double worst = 0.0;
    for (int i = 0; i < FRAMES; i++) {
        const double want = (double)pl[i] * 16384.0;
        const double got  = (double)mv[i * 2];
        const double d = fabs(got - want);
        if (d > worst) { worst = d; worst_at = i; }
    }

    const uint64_t h = fnv1a(pl, sizeof pl);

    if (dump) {
        printf("plugin-path hash: 0x%016llXull\n", (unsigned long long)h);
        printf("worst A/B difference: %.3f LSB at sample %d\n", worst, worst_at);
        return 0;
    }

    int fail = 0;

    /*
     * ONE LSB, which is the theoretical best for int16 and what the two paths
     * actually achieve (0.976 as measured). Anything larger is the two paths
     * applying different GAINS, which is what this exists to catch.
     *
     * It was 1.5 while the int16 path truncated instead of rounding -- 1.47
     * measured, a hair under the threshold. A tolerance that a correct build
     * only just clears is a tolerance that will fail on somebody else's
     * compiler, so the path was fixed rather than the number raised.
     */
    if (worst > 1.0) {
        fprintf(stderr,
                "A/B FAILED: the two paths differ by %.3f LSB at sample %d\n"
                "  the plugin path and the Move path are applying different gains\n",
                worst, worst_at);
        fail = 1;
    } else {
        printf("A/B ok: worst difference %.3f LSB (sample %d)\n", worst, worst_at);
    }

    if (GOLDEN == 0ull) {
        fprintf(stderr,
                "GOLDEN is unset -- run with --dump and record the hash.\n");
        fail = 1;
    } else if (h != GOLDEN) {
        fprintf(stderr,
                "GOLDEN FAILED: 0x%016llX, expected 0x%016llX\n"
                "  the DSP changed. Re-run with --dump, decide whether that was\n"
                "  intended, and record the new value with a reason.\n",
                (unsigned long long)h, (unsigned long long)GOLDEN);
        fail = 1;
    } else {
        printf("golden ok: 0x%016llX\n", (unsigned long long)h);
    }

    printf(fail ? "\nFAILED\n" : "\nPASS\n");
    return fail;
}
