// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Torben Gräber

/*
 * Generates the curve fixture the engine's shape maths is pinned to.
 *
 * THE FIXTURE IS GENERATED BY THE ENGINE. The web editor once kept a second
 * copy of the maths in JavaScript, pinned to this same file rather than to
 * the C, because two identically-wrong transcriptions agree with each other
 * perfectly. The native editor draws the engine's own shape, so the fixture
 * now keeps a change to that maths a decision.
 *
 * Regenerate with
 *
 *     sc_shape_table > engines/side-chain/tests/fixtures/shape_table.txt
 *
 * and ONLY when the curve maths is meant to change. A regenerated fixture that
 * nobody intended is a test that has stopped testing.
 *
 * Format: one row per sample, "curve t value inverse", space separated, with t
 * at 1/1000 steps. The inverse is included so the engine's inverse is pinned
 * as well as its forward direction.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "sc_core.h"

#define STEPS 1000

/*
 * TWO MODES, AND THE SECOND ONE IS THE TEST.
 *
 *   sc_shape_table                     print the fixture
 *   sc_shape_table --verify <file>     check the engine still agrees with it
 *
 * The second is what ctest runs.
 *
 * TOL is 0: the generator wrote %.17g, which round-trips a double exactly, and
 * this is the same engine computing the same expression. Anything other than
 * equality here means the maths moved.
 */
static int verify(const char *path)
{
    FILE *f = fopen(path, "r");
    if (!f) { fprintf(stderr, "cannot open %s\n", path); return 2; }

    char line[512];
    int rows = 0, bad = 0;
    while (fgets(line, sizeof line, f)) {
        if (line[0] == '#' || line[0] == '\n') continue;
        int curve;
        double t, want_s, want_i;
        if (sscanf(line, "%d %lf %lf %lf", &curve, &t, &want_s, &want_i) != 4)
            continue;
        const double got_s = sc_test_shape(curve, t);
        const double got_i = sc_test_shape_inv(curve, t);
        if (got_s != want_s || got_i != want_i) {
            if (bad < 10)
                fprintf(stderr, "curve %d t=%.17g: shape %.17g vs %.17g, "
                        "inv %.17g vs %.17g\n",
                        curve, t, got_s, want_s, got_i, want_i);
            bad++;
        }
        rows++;
    }
    fclose(f);

    /* A fixture that has quietly emptied passes every comparison in it. */
    if (rows < 3000) {
        fprintf(stderr, "only %d rows -- the fixture looks truncated\n", rows);
        return 1;
    }
    printf("%s: %d rows, %d mismatched\n", path, rows, bad);
    return bad ? 1 : 0;
}

int main(int argc, char **argv)
{
    if (argc >= 3 && strcmp(argv[1], "--verify") == 0)
        return verify(argv[2]);

    printf("# curve t shape inverse\n");
    printf("# curves: 0 Linear, 1 Exponential, 2 S-Curve\n");
    for (int curve = 0; curve < 3; curve++) {
        for (int i = 0; i <= STEPS; i++) {
            const double t = (double)i / (double)STEPS;
            /* %.17g is the shortest decimal that round-trips a double exactly,
             * so the fixture cannot quantise what it is pinning. */
            printf("%d %.17g %.17g %.17g\n", curve, t,
                   sc_test_shape(curve, t),
                   sc_test_shape_inv(curve, t));
        }
    }
    return 0;
}
