/*
 * Generates the curve fixture that BOTH copies of the shape maths are pinned
 * to -- the C one here and the JavaScript one in plugins/side-chain/ui/src/lib.
 *
 * THE FIXTURE IS GENERATED BY THE ENGINE, AND NEITHER COPY IS COMPARED
 * AGAINST THE OTHER. That is the whole design: comparing them to each other
 * proves only that they agree, which two identically-wrong transcriptions also
 * do. Pinning each to the engine's own output proves they agree WITH THE THING
 * THAT MAKES THE SOUND.
 *
 * Regenerate with
 *
 *     ./build/engines/side-chain/sc_shape_table > plugins/side-chain/ui/test/shape_table.txt
 *
 * and ONLY when the curve maths is meant to change. A regenerated fixture that
 * nobody intended is a test that has stopped testing.
 *
 * Format: one row per sample, "curve dir t value inverse", space separated,
 * with t at 1/1000 steps. The inverse is included so a JS port cannot pass by
 * implementing only the forward direction.
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>
#include "sc_core.h"

#define STEPS 1000

/*
 * TWO MODES, AND THE SECOND ONE IS THE TEST.
 *
 *   sc_shape_table                     print the fixture
 *   sc_shape_table --verify <file>     check the engine still agrees with it
 *
 * The second is what ctest runs. Without it the fixture would only ever be
 * checked from JavaScript, and a change to the Rust would be caught on one side
 * of a contract that has two.
 *
 * TOL is 0: the generator wrote %.17g, which round-trips a double exactly, and
 * this is the same engine computing the same expression. Anything other than
 * equality here means the maths moved.
 */
static int verify(const char *path)
{
    FILE *f = fopen(path, "r");
    if (!f) { fprintf(stderr, "cannot open %s\n", path); return 2; }

    char line[512];
    int rows = 0, bad = 0;
    while (fgets(line, sizeof line, f)) {
        if (line[0] == '#' || line[0] == '\n') continue;
        int curve, dir;
        double t, want_s, want_i;
        if (sscanf(line, "%d %d %lf %lf %lf", &curve, &dir, &t, &want_s, &want_i) != 5)
            continue;
        const double got_s = sc_test_shape(curve, t, dir);
        const double got_i = sc_test_shape_inv(curve, t, dir);
        if (got_s != want_s || got_i != want_i) {
            if (bad < 10)
                fprintf(stderr, "curve %d dir %d t=%.17g: shape %.17g vs %.17g, "
                        "inv %.17g vs %.17g\n",
                        curve, dir, t, got_s, want_s, got_i, want_i);
            bad++;
        }
        rows++;
    }
    fclose(f);

    /* A fixture that has quietly emptied passes every comparison in it. */
    if (rows < 8000) {
        fprintf(stderr, "only %d rows -- the fixture looks truncated\n", rows);
        return 1;
    }
    printf("%s: %d rows, %d mismatched\n", path, rows, bad);
    return bad ? 1 : 0;
}

int main(int argc, char **argv)
{
    if (argc >= 3 && strcmp(argv[1], "--verify") == 0)
        return verify(argv[2]);

    printf("# curve dir t shape inverse\n");
    printf("# curves: 0 Linear, 1 Exponential, 2 S-Curve, 3 Pump\n");
    printf("# dir: 0 down (the duck deepening), 1 up (the recovery)\n");
    for (int curve = 0; curve < 4; curve++) {
        for (int dir = 0; dir < 2; dir++) {
            for (int i = 0; i <= STEPS; i++) {
                const double t = (double)i / (double)STEPS;
                /* %.17g is the shortest decimal that round-trips a double
                 * exactly, so the fixture cannot quantise what it is pinning. */
                printf("%d %d %.17g %.17g %.17g\n", curve, dir, t,
                       sc_test_shape(curve, t, dir),
                       sc_test_shape_inv(curve, t, dir));
            }
        }
    }
    return 0;
}
