// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Torben Gräber

/*
 * A C ABI held to a header it used to have.
 *
 * The engines' headers are generated by cbindgen from the Rust
 * (engines/shared/cbindgen/capi_header.rs), and a generated header is only as
 * compatible as the Rust behind it: a `*const` that should have been `*mut`,
 * an enum that became an int, a constant that lost its value -- each of those
 * is a header that still compiles and a caller that no longer does. The
 * Trance Gate's tg_* surface has a caller that is not in this repository at
 * all, the archived Max for Live external (tag archive/trance-gate-m4l), so
 * its last hand-written headers are kept as fixtures and the generated ones
 * are held to them here, in two halves:
 *
 *   names   the tg_* functions the generated headers declare are exactly the
 *           ones the fixtures declare: nothing lost, nothing new by accident.
 *           Run by ctest, it reads the headers the build generated.
 *
 *   emit    writes a C++ file in which every fixture declaration is a
 *           static_assert against the generated header: each function's type
 *           (return and parameter types, const and enums included -- names do
 *           not count), each macro's value and type, each enum constant's
 *           value, each struct's size and every field's offset and type, each
 *           function pointer typedef, each opaque handle's name and struct
 *           tag. The COMPILER does the
 *           comparing, so "the same" means what C++ means by it, and the
 *           build fails on the first difference with the name in the message.
 *
 *   node tests/capi-compat.mjs names --prefix tg_ --fixture <old.h>... --header <new.h>...
 *   node tests/capi-compat.mjs emit --fixture <old.h>... --include <new.h>... --out <file.cpp>
 *
 * The parser below reads the C these headers are written in -- prototypes,
 * typedefs, enums, object-like macros -- and nothing more general; a fixture
 * is frozen, so it only ever has to read what is in it.
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { basename } from 'node:path';

/* Comments out, with string literals left alone (extern "C" is one). */
function stripComments(text) {
  return text.replace(/"(?:\\.|[^"\\])*"|\/\*[\s\S]*?\*\/|\/\/[^\n]*/g,
    (m) => (m.startsWith('"') ? m : ' '));
}

const squash = (s) => s.replace(/\s+/g, ' ').trim();

/* What one header declares. */
export function parse(text) {
  const out = {
    functions: new Map(),   // name -> { ret, params }
    macros: new Map(),      // name -> value text
    enums: [],              // { name | null, consts: [[name, value]] }
    structs: new Map(),     // name -> [field declaration]
    fnptrs: new Map(),      // name -> { ret, params }
    opaque: new Map(),      // name -> tag, of `typedef struct tag name;`
  };
  const lines = [];
  for (const line of stripComments(text).split('\n')) {
    const define = /^\s*#\s*define\s+([A-Za-z_]\w*)(?!\()\s+(.+?)\s*$/.exec(line);
    if (define) out.macros.set(define[1], define[2]);
    if (!/^\s*#/.test(line)) lines.push(line);
  }
  /* extern "C" { ... } is a wrapper, not a declaration. */
  let body = lines.join('\n').replace(/extern\s+"C"\s*\{/g, ' ');

  /* Top-level declarations: split at `;` and at the `}` that closes a
   * function body, at brace depth zero. A stray `}` (extern "C"'s) is
   * dropped. */
  const decls = [];
  let depth = 0;
  let current = '';
  for (const ch of body) {
    if (ch === '{') depth++;
    if (ch === '}') {
      if (depth === 0) continue;
      depth--;
      current += ch;
      if (depth === 0 && /\)\s*\{[\s\S]*\}$/.test(current) && !/^\s*typedef/.test(current)
          && !/^\s*enum\b/.test(current)) {
        decls.push(current);
        current = '';
      }
      continue;
    }
    if (ch === ';' && depth === 0) {
      decls.push(current);
      current = '';
      continue;
    }
    current += ch;
  }

  for (const raw of decls.map(squash).filter(Boolean)) {
    let m;
    if ((m = /^typedef enum(?: \w+)? ?\{(.*)\} ?(\w+)$/.exec(raw))) {
      out.enums.push({ name: m[2], consts: enumConsts(m[1]) });
    } else if ((m = /^enum(?: \w+)? ?\{(.*)\}$/.exec(raw))) {
      out.enums.push({ name: null, consts: enumConsts(m[1]) });
    } else if ((m = /^typedef struct(?: \w+)? ?\{(.*)\} ?(\w+)$/.exec(raw))) {
      out.structs.set(m[2], m[1].split(';').map(squash).filter(Boolean));
    } else if ((m = /^typedef struct (\w+) (\w+)$/.exec(raw))) {
      out.opaque.set(m[2], m[1]);
    } else if ((m = /^typedef (.+?)\(\s*\*\s*(\w+)\s*\)\s*\((.*)\)$/.exec(raw))) {
      out.fnptrs.set(m[2], { ret: squash(m[1]), params: squash(m[3]) });
    } else if ((m = /^(?:static )?(?:inline )?(.+?)\b(\w+)\s*\(([^()]*)\)(?:\s*\{.*\})?$/.exec(raw))) {
      out.functions.set(m[2], { ret: squash(m[1]), params: squash(m[3]) || 'void' });
    } else {
      throw new Error(`capi-compat: cannot read this declaration: ${raw}`);
    }
  }
  return out;
}

/* An enum body's constants, with C's implicit numbering made explicit: a
 * number where the fixture counts from a literal, an expression otherwise. */
function enumConsts(body) {
  const consts = [];
  let next = 0;
  for (const item of body.split(',').map(squash).filter(Boolean)) {
    const [name, value] = item.split('=').map(squash);
    const v = value === undefined ? next
      : /^-?\d+$/.test(value) ? Number(value) : value;
    consts.push([name, String(v)]);
    next = typeof v === 'number' ? v + 1 : `(${v}) + 1`;
  }
  return consts;
}

function readAll(files) {
  const merged = parse('');
  for (const f of files) {
    const p = parse(readFileSync(f, 'utf8'));
    for (const key of ['functions', 'macros', 'structs', 'fnptrs', 'opaque']) {
      for (const [k, v] of p[key]) merged[key].set(k, v);
    }
    merged.enums.push(...p.enums);
  }
  return merged;
}

/* Include guards are the header's own business, not its surface. */
const isGuard = (name, value) => value === undefined || /_H$/.test(name);

function emit({ fixture, include, out }) {
  const fx = readAll(fixture);
  const id = (s) => s.replace(/\W/g, '_');
  const lines = [
    '// SPDX-License-Identifier: GPL-3.0-or-later',
    '// Copyright (C) 2026 Torben Gräber',
    '',
    `// Generated by tests/capi-compat.mjs from ${fixture.map((f) => basename(f)).join(', ')}.`,
    '// Every assertion is one declaration of the fixture, checked against the',
    '// generated header the build includes below.',
    '#include <cstddef>',
    '#include <cstdint>',
    '#include <cstdio>',
    '#include <type_traits>',
    ...include.map((h) => `#include "${basename(h)}"`),
    '',
  ];
  let n = 0;
  const check = (cond, what) => {
    lines.push(`static_assert(${cond}, ${JSON.stringify(what)});`);
    n++;
  };

  for (const [name, { ret, params }] of fx.functions) {
    check(`std::is_same<decltype(&${name}), ${ret} (*)(${params})>::value`,
      `${name}: its type is not the fixture's ${ret} (${params})`);
  }
  for (const [name, value] of fx.macros) {
    if (isGuard(name, value)) continue;
    check(`(${name}) == (${value})`, `${name} is not ${value}`);
    /* And of the same type: 200.0 equals 200.0f, but a double where a float
     * was turns every expression a caller builds from it into a double. */
    check(`std::is_same<decltype(${name}), decltype(${value})>::value`,
      `${name} is not of ${value}'s type`);
  }
  for (const { name, consts } of fx.enums) {
    if (name) {
      check(`std::is_enum<${name}>::value`, `${name} is not an enum`);
    }
    for (const [c, v] of consts) {
      if (name) check(`std::is_same<decltype(${c}), ${name}>::value`, `${c} is not a ${name}`);
      check(`(${c}) == (${v})`, `${c} is not ${v}`);
    }
  }
  for (const [name, fields] of fx.structs) {
    const copy = `fixture_${id(name)}`;
    lines.push(`struct ${copy} { ${fields.map((f) => `${f};`).join(' ')} };`);
    check(`sizeof(${name}) == sizeof(${copy})`, `${name}'s size is not the fixture's`);
    for (const field of fields) {
      const fieldName = /(\w+)\s*(?:\[[^\]]*\])?$/.exec(field)[1];
      check(`offsetof(${name}, ${fieldName}) == offsetof(${copy}, ${fieldName})`,
        `${name}.${fieldName} is not where the fixture has it`);
      check(`std::is_same<decltype(${name}::${fieldName}), decltype(${copy}::${fieldName})>::value`,
        `${name}.${fieldName}'s type is not the fixture's`);
    }
  }
  for (const [name, { ret, params }] of fx.fnptrs) {
    check(`std::is_same<${name}, ${ret} (*)(${params})>::value`,
      `${name} is not the fixture's ${ret} (*)(${params})`);
  }
  /* A handle's struct tag is part of its surface: a caller may forward-declare
   * it, or spell `struct tag *`. Named here and not declared by the header,
   * `struct tag` is a new, different type, so the assert fails. */
  for (const [name, tag] of fx.opaque) {
    check(`sizeof(${name} *) == sizeof(void *)`, `${name} is not declared`);
    check(`std::is_same<struct ${tag}, ${name}>::value`, `${name} is not struct ${tag}`);
  }

  lines.push('', 'int main() {',
    `    std::printf("%d declarations of ${fixture.map((f) => basename(f)).join(', ')} hold\\n", ${n});`,
    '    return 0;', '}', '');
  writeFileSync(out, lines.join('\n'));
}

function names({ prefix, fixture, header }) {
  const pick = (files) => new Set([...readAll(files).functions.keys()]
    .filter((name) => name.startsWith(prefix)));
  const before = pick(fixture);
  const now = pick(header);
  const lost = [...before].filter((n) => !now.has(n));
  const added = [...now].filter((n) => !before.has(n));
  for (const n of lost) console.error(`lost: ${n} -- a caller of the fixture's surface no longer links`);
  for (const n of added) {
    console.error(`new: ${n} -- source-compatible, but the surface is pinned: add its prototype ` +
      'to the fixture, below the line that marks what was there before, if it is meant');
  }
  if (lost.length || added.length) process.exit(1);
  console.log(`${now.size} ${prefix}* functions, the same set as ${fixture.map((f) => basename(f)).join(', ')}`);
}

function args(argv) {
  const opts = { fixture: [], include: [], header: [] };
  for (let i = 0; i < argv.length; i += 2) {
    const key = argv[i].replace(/^--/, '');
    if (Array.isArray(opts[key])) opts[key].push(argv[i + 1]);
    else opts[key] = argv[i + 1];
  }
  return opts;
}

if (process.argv[1] && process.argv[1].endsWith('capi-compat.mjs')) {
  const [mode, ...rest] = process.argv.slice(2);
  const opts = args(rest);
  if (mode === 'emit') emit(opts);
  else if (mode === 'names') names(opts);
  else {
    console.error('usage: capi-compat.mjs names|emit ... (see the comment at the top)');
    process.exit(2);
  }
}
