/*
 * Print the engine's `ui` readout for a known patch, as a fixture.
 *
 * WHY A FIXTURE AND NOT AN ASSERTION IN JAVASCRIPT. Two things decode this
 * string -- the WebView editor and the Max for Live device's grid, both
 * through plugins/trance-gate/ui/src/lib/readout.js -- and neither of them
 * can run the engine. A JavaScript test that built its own input would be
 * testing the decoder against the test author's belief about the format,
 * which is precisely the failure this repository already paid for once: the
 * JS copy of shape() had the S-curve's first half un-mirrored for as long as
 * it existed, because nothing compared it to the engine.
 *
 * So the engine prints, the fixture records, and the decoder is checked
 * against THAT. It is the same arrangement tests/shape_table.c has with
 * ui/test/shape_table.txt, and the comment in tests/CMakeLists.txt explaining
 * that one applies here word for word: both sides are pinned to one table
 * generated BY THE ENGINE, and neither is compared against the other.
 *
 * Regenerate with `tg_ui_readout > plugins/trance-gate-m4l/ui/test/readout_table.txt`
 * and only when the readout format is MEANT to change -- at which point both
 * decoders have to move with it, which is the point of the test failing.
 */
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "trance_gate_core.h"

/*
 * --verify compares against the fixture instead of writing it, so the table
 * cannot go stale unnoticed: a readout format change fails HERE, next to the
 * engine that moved, rather than in a JavaScript test that has no way to say
 * which side is wrong.
 */
static FILE *want = NULL;
static int fail = 0;

static void line(const char *text) {
    if (!want) { printf("%s", text); return; }
    char got[TG_STATE_MAX + 256];
    if (!fgets(got, (int) sizeof got, want)) {
        printf("  FIXTURE IS SHORT, missing: %s", text);
        fail = 1;
        return;
    }
    if (strcmp(got, text) != 0) {
        printf("  FIXTURE DIFFERS\n    want %s    got  %s", got, text);
        fail = 1;
    }
}

static void emit(tg_core_t *c, const char *what) {
    char buf[TG_STATE_MAX], out[TG_STATE_MAX + 256];
    if (tg_core_get_param(c, "ui", buf, (int) sizeof buf) < 0) {
        printf("# %s: the engine does not serve `ui`\n", what);
        fail = 1;
        return;
    }
    snprintf(out, sizeof out, "%s\t%s\n", what, buf);
    line(out);
}

int main(int argc, char **argv) {
    if (argc > 2 && strcmp(argv[1], "--verify") == 0) {
        want = fopen(argv[2], "r");
        if (!want) { printf("  cannot read %s\n", argv[2]); return 1; }
    }
    tg_core_t *c = tg_core_create(44100.0);

    line("# The engine's `ui` readout. Generated by tests/ui_readout.c --\n");
    line("# do not edit. Fields: steps:ties:length:pos:ms_per_step:"
         "advancing:cursor:depths:orders\n");

    /*
     * A 16-STEP PATTERN THAT IS NOT SYMMETRICAL, which matters: the step and
     * tie bitmaps are little-endian hex and a palindrome would decode the
     * same read forwards or backwards. BEEF does not.
     */
    tg_core_set_param(c, "rate",    "1/16");
    tg_core_set_param(c, "length",  "15");
    tg_core_set_param(c, "pattern", "BEEF");
    tg_core_set_param(c, "ties",    "0022");
    emit(c, "beef16");

    /*
     * A LENGTH THAT IS NOT A MULTIPLE OF FOUR. A decoder that reads the hex
     * forwards is correct exactly when the length fills whole nibbles, so a
     * 13-step pattern is where that bug becomes visible.
     */
    tg_core_set_param(c, "length",  "12");
    emit(c, "beef13");

    /* Per-step depths, ascending, so a decoder that reads the run backwards
     * or at the wrong stride disagrees on every step but the middle. */
    tg_core_set_param(c, "length", "15");
    for (int s = 0; s < 16; s++) {
        char v[16];
        snprintf(v, sizeof v, "%d", s);
        tg_core_set_param(c, "cursor", v);
        snprintf(v, sizeof v, "%.3f", 0.05 + 0.06 * s);
        tg_core_set_param(c, "step_amount", v);
    }
    tg_core_set_param(c, "cursor", "3");
    emit(c, "depths");

    /* An empty pattern, which is the one a decoder is most likely to invent
     * a default for rather than report honestly. */
    tg_core_set_param(c, "pattern", "0");
    tg_core_set_param(c, "ties",    "0");
    emit(c, "empty");

    tg_core_destroy(c);

    if (want) {
        fclose(want);
        if (fail) {
            printf("  Regenerate with:\n"
                   "    tg_ui_readout > plugins/trance-gate-m4l/ui/test/readout_table.txt\n"
                   "  and move BOTH decoders with it -- readout.js is shared.\n");
            return 1;
        }
        printf("  the engine still emits the readout the decoders expect  ok\n");
    }
    return 0;
}
