/*
 * Install NI Trance Gate Live into Max and Live.
 * Copyright (c) 2026 Torben Gräber. MIT.
 *
 *   node plugins/trance-gate-live/install.mjs [--uninstall]
 *
 * WHY AN INSTALL STEP EXISTS AT ALL, when the plugin's three formats just get
 * copied into ~/Library/Audio/Plug-Ins by the build. A Max for Live device is
 * three separate things that have to find each other, and only one of them is
 * a file Live looks for:
 *
 *   the .amxd       Live finds it in the User Library
 *   the external    Max finds it on ITS search path, which Live does not set
 *   the v8ui        Max finds it the same way, and it has IMPORTS
 *
 * THE IMPORTS ARE THE WHOLE REASON THIS IS NOT THREE `cp` COMMANDS. grid.js
 * imports readout.js from the WebView editor's tree -- deliberately, because
 * a second decoder is the bug this repository has already paid for once --
 * and that relative path exists only inside a checkout. Copying grid.js
 * somewhere Max can see it produces a v8ui that loads and then fails on its
 * first import, which in Max is a silent blank rectangle.
 *
 * So the grid is BUNDLED: esbuild follows the imports and emits one file with
 * no import statements left in it. That is also what freezing the device will
 * need, so it is not a detour.
 *
 * A MAX PACKAGE, not loose files in the Max search path. A package is a
 * folder with `externals/` and `javascript/` in it, and everything inside is
 * on the path automatically -- so this puts one directory in place and
 * removes one directory to undo, rather than scattering files that outlive
 * whoever remembers putting them there. --uninstall does exactly that.
 */
import { execFileSync } from 'node:child_process';
import { cpSync, existsSync, mkdirSync, rmSync, readdirSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { homedir } from 'node:os';

const here = dirname(fileURLToPath(import.meta.url));
const ROOT = join(here, '..', '..');
const HOME = homedir();

const NAME = 'NI Trance Gate Live';
const DEVICE = `${NAME}.amxd`;

/*
 * WHICH MAX, and it is not ours to assume. Live Suite bundles its own Max and
 * a user may also have a standalone one; the packages folder is per major
 * version, so a hard-coded "Max 9" is wrong the day 10 ships. Take the
 * highest that exists, and say which.
 */
const maxDirs = existsSync(join(HOME, 'Documents'))
  ? readdirSync(join(HOME, 'Documents'))
      .filter((d) => /^Max \d+$/.test(d))
      .sort((a, b) => Number(b.split(' ')[1]) - Number(a.split(' ')[1]))
  : [];

if (!maxDirs.length) {
  console.error('No "~/Documents/Max <n>" folder -- open Max once so it '
              + 'creates one, then run this again.');
  process.exit(1);
}
const MAX = join(HOME, 'Documents', maxDirs[0]);
const PKG = join(MAX, 'Packages', NAME);

/*
 * Live's User Library. A Max audio effect belongs beside the other Audio
 * Effect presets, which is where Live's browser looks for user devices.
 */
const LIVE = join(HOME, 'Music', 'Ableton', 'User Library',
                  'Presets', 'Audio Effects', 'Max Audio Effect');

/* ------------------------------------------------------------------ */

if (process.argv.includes('--uninstall')) {
  for (const p of [PKG, join(LIVE, DEVICE)]) {
    if (existsSync(p)) { rmSync(p, { recursive: true }); console.log(`removed ${p}`); }
    else console.log(`not there: ${p}`);
  }
  process.exit(0);
}

const mxo = join(here, 'externals', 'ni.trancegate~.mxo');
const amxd = join(here, DEVICE);

for (const [what, p] of [['the external', mxo], ['the device', amxd]]) {
  if (!existsSync(p)) {
    console.error(`${what} is missing: ${p}\n`
      + '  cmake -B build -DTG_BUILD_LIVE=ON && '
      + 'cmake --build build --target ni.trancegate_tilde\n'
      + '  node plugins/trance-gate-live/build-device.mjs');
    process.exit(1);
  }
}

mkdirSync(join(PKG, 'externals'), { recursive: true });
mkdirSync(join(PKG, 'javascript'), { recursive: true });
mkdirSync(LIVE, { recursive: true });

/* The external, whole -- it is a bundle, not a file. */
rmSync(join(PKG, 'externals', 'ni.trancegate~.mxo'), { recursive: true, force: true });
cpSync(mxo, join(PKG, 'externals', 'ni.trancegate~.mxo'), { recursive: true });

/*
 * The grid, bundled. `format: esm` because v8ui is an ES-module context;
 * `bundle` is what resolves readout.js out of the editor's tree and inlines
 * it. No minify: this lands in a user's Packages folder, where being
 * readable is worth more than being small, and nothing here is hot.
 */
execFileSync(join(ROOT, 'node_modules', '.bin', 'esbuild'), [
  join(here, 'ui', 'grid.js'),
  '--bundle',
  '--format=esm',
  '--platform=neutral',
  `--outfile=${join(PKG, 'javascript', 'grid.js')}`,
  '--banner:js=/* GENERATED by plugins/trance-gate-live/install.mjs -- edit '
    + 'the sources in that directory, not this file. */',
], { stdio: 'inherit' });

cpSync(amxd, join(LIVE, DEVICE));

console.log(`Max ${maxDirs[0]}`);
console.log(`  package  ${PKG}`);
console.log(`  device   ${join(LIVE, DEVICE)}`);
console.log('\nRestart Live (Max only scans Packages at startup), then find '
          + `"${NAME}"\nunder Audio Effects > Max Audio Effect in the browser.`);
