// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Torben Gräber
//
// NI Chord-Detector's engine, as C. GENERATED by cbindgen from
// engines/chord-detector/crates/cd-capi/src/lib.rs -- edit that, never this.

#ifndef CD_CAPI_H
#define CD_CAPI_H

#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>

// The longest readout, in bytes with its NUL.
#define CD_NAME_MAX 32

// The longest line under it.
#define CD_DESCRIPTION_MAX 96

// The longest roman numeral.
#define CD_DEGREE_MAX 16

// The longest list of sounding notes. Sixty notes fit; more end the list
// early, which a display has no room for anyway.
#define CD_NOTES_MAX 320

// The longest key name, "F# Mixolydian".
#define CD_KEY_MAX 24

// The most alternative readings.
#define CD_ALTERNATIVES 8

// The longest alternative reading.
#define CD_ALTERNATIVE_MAX 24

// The opaque engine handle the audio thread holds between begin and end.
typedef struct CdCore CdCore;

// The handle a plugin instance holds.
typedef struct CdShell CdShell;

// What the editor draws from, published by the audio thread.
//
// Every text is UTF-8 and NUL-terminated. Note sets are 128 bits, two words,
// note `n` at bit `n % 64` of word `n / 64`.
typedef struct CdReading {
  // Changes whenever anything below the clock does.
  uint32_t serial;
  // 0 empty, 1 note, 2 interval, 3 chord, 4 a set with no name.
  uint8_t kind;
  // 1 when the reading is shown because Hold kept it after release.
  uint8_t held;
  // 1 while the sustain pedal is down.
  uint8_t pedal;
  // 1 while the host's transport plays.
  uint8_t playing;
  // The chord's root as a pitch class, or -1.
  int8_t root;
  // The reading's lowest note, or -1.
  int8_t bass;
  // The reading's pitch classes, C at bit 0.
  uint16_t pitch_classes;
  // The notes the reading was taken from. Under Hold, after release, these
  // are the held chord's.
  uint64_t notes[2];
  // The notes sounding now.
  uint64_t sounding[2];
  // The key: tonic 0-11, mode 0-6 (Ionian to Locrian), its signature (-5
  // flats to 6 sharps), its pitch classes, and the Spelling choice the
  // texts were written with (0 the key's way, 1 sharps, 2 flats) -- what
  // `cd_write_note` takes to name the history's notes the same way.
  uint8_t tonic;
  uint8_t mode;
  int8_t signature;
  uint8_t spelling;
  uint16_t scale;
  // How many of `alternatives` are filled.
  uint8_t alternative_count;
  // The history's clock: now, in quarters; its tempo; the bar's length in
  // quarters; and a point on the clock where a bar begins.
  double now;
  double bpm;
  double bar;
  double bar_origin;
  // Note events that did not fit the ring since the instance began.
  uint32_t dropped;
  char name[CD_NAME_MAX];
  char description[CD_DESCRIPTION_MAX];
  char degree[CD_DEGREE_MAX];
  char notes_text[CD_NOTES_MAX];
  char key_name[CD_KEY_MAX];
  char alternatives[CD_ALTERNATIVES][CD_ALTERNATIVE_MAX];
} CdReading;

// One note starting (`velocity` > 0) or stopping (`velocity` 0), at `at`
// quarters on the history's clock.
typedef struct CdNoteEvent {
  double at;
  uint8_t note;
  uint8_t velocity;
} CdNoteEvent;

// What a shell declares one parameter with.
typedef struct CdParamInfo {
  int32_t choice_count;
  int32_t default_choice;
  bool automatable;
} CdParamInfo;

// How a score writes one note: what a staff needs to place it.
typedef struct CdWrittenNote {
  // The letter, 0 C to 6 B.
  uint8_t letter;
  // Sharps positive, flats negative, -2 to 2.
  int8_t accidental;
  // The written octave: C flat 4 sounds as B 3.
  int16_t octave;
  // Letter steps up from C in octave 0: one per line and per space.
  int32_t staff_step;
  // The name with its octave, `Bb3`.
  char name[8];
} CdWrittenNote;

// What a key is, for drawing it: its seven pitch classes (C at bit 0) and
// its signature, -5 flats to 6 sharps.
typedef struct CdKey {
  uint16_t scale;
  int8_t signature;
} CdKey;

#ifdef __cplusplus
extern "C" {
#endif // __cplusplus

// A new engine at `sample_rate` (44.1 kHz if that is not positive), every
// parameter at its default. Construction only: it allocates.
struct CdShell *cd_shell_create(double sample_rate);

// # Safety
// `shell` is null or from `cd_shell_create`, and no thread uses it after.
void cd_shell_destroy(struct CdShell *shell);

// The host's rate, applied at the top of the next block. Not the audio
// thread. A rate that is not positive is ignored.
//
// # Safety
// `shell` is null or live.
void cd_shell_post_sample_rate(const struct CdShell *shell, double sample_rate);

// Every note stops and a held reading clears, at the top of the next block:
// what a shell posts when the host (re)activates it, since a deactivated
// plugin hears no note-offs. Not the audio thread.
//
// # Safety
// `shell` is null or live.
void cd_shell_post_reset(const struct CdShell *shell);

// The audio thread, at the top of a block: the engine, for this block only.
//
// # Safety
// `shell` is null or live; the audio thread only, one block at a time; the
// pointer is not used after `cd_shell_end`.
struct CdCore *cd_shell_begin(const struct CdShell *shell);

// The audio thread, at the end of a block of `frames`: publishes a frame
// when one is due.
//
// # Safety
// As `cd_shell_begin`, after it.
void cd_shell_end(const struct CdShell *shell, uint32_t frames);

// Copy the latest reading into `out`. Not the audio thread. Returns false
// when there is nothing to copy into or from.
//
// # Safety
// `shell` is null or live; `out` is null or writable.
bool cd_shell_read(const struct CdShell *shell, struct CdReading *out);

// Move up to `max` note events, oldest first, into `out`; returns how many.
// The message thread.
//
// # Safety
// `shell` is null or live; `out` is null or has room for `max` events.
size_t cd_shell_drain(const struct CdShell *shell, struct CdNoteEvent *out, size_t max);

// The host's clock for this block. `has_clock` 0 means the host reported
// nothing; the history then runs at its last tempo.
//
// # Safety
// `core` is null or from `cd_shell_begin`, inside that block.
void cd_core_begin_block(struct CdCore *core,
                         int32_t has_clock,
                         double ppq,
                         double bpm,
                         int32_t num,
                         int32_t den,
                         int32_t playing);

// One MIDI message of `len` bytes, `offset` samples into the block.
//
// # Safety
// `core` as `cd_core_begin_block`; `bytes` is null or holds `len` bytes.
void cd_core_on_midi(struct CdCore *core, const uint8_t *bytes, size_t len, uint32_t offset);

// Set parameter `index` to `choice` (clamped). Cheap when nothing changes,
// so a shell may pass every parameter every block.
//
// # Safety
// `core` as `cd_core_begin_block`.
void cd_core_set_param(struct CdCore *core, int32_t index, int32_t choice);

// A panic from the shell: every note stops and a held reading clears.
//
// # Safety
// `core` as `cd_core_begin_block`.
void cd_core_reset(struct CdCore *core);

// The bottom of the block: the history's clock moves on by `frames`.
//
// # Safety
// `core` as `cd_core_begin_block`, before `cd_shell_end`.
void cd_core_end_block(struct CdCore *core, uint32_t frames);

// How many parameters there are.
int32_t cd_param_count(void);

// Describe parameter `index`. Any thread. False for an index out of range.
//
// # Safety
// `out` is null or writable.
bool cd_param_info(int32_t index, struct CdParamInfo *out);

// Parameter `index`'s stable key, as a saved state names it, into `out`.
// Returns its length, or -1 when the index is out of range or `cap` too
// small. Any thread.
//
// # Safety
// `out` is null or has room for `cap` bytes.
int32_t cd_param_key(int32_t index, char *out, size_t cap);

// Parameter `index`'s display name, as `cd_param_key`.
//
// # Safety
// As `cd_param_key`.
int32_t cd_param_name(int32_t index, char *out, size_t cap);

// The label of choice `choice` of parameter `index`, as `cd_param_key`.
//
// # Safety
// As `cd_param_key`.
int32_t cd_param_choice(int32_t index, int32_t choice, char *out, size_t cap);

// How MIDI note `midi` is written in the key `tonic` (0-11) / `mode` (0-6)
// under Spelling choice `spelling` (0 the key's way, 1 sharps, 2 flats) --
// the same naming the reading's texts use. Any thread; a pure function.
// Out-of-range values are clamped.
struct CdWrittenNote cd_write_note(int32_t tonic, int32_t mode, int32_t spelling, int32_t midi);

// The key `tonic` (0-11) / `mode` (0-6, Ionian to Locrian), as the engine
// reads in it: what an editor draws from its parameters while the engine has
// not run a block with them yet. Any thread; a pure function. Out-of-range
// values are clamped.
struct CdKey cd_key_info(int32_t tonic, int32_t mode);

#ifdef __cplusplus
}  // extern "C"
#endif  // __cplusplus

#endif  /* CD_CAPI_H */
