/*
 * The duck the shaper draws: a port of `engines/side-chain/crates/sc-core/src/shape.rs`,
 * on the kit's curve.
 *
 * Plain JavaScript with no JSX and no imports, on purpose: this is the one
 * piece of the editor that must agree with the DSP to the digit, so it has to
 * be loadable by `node --test` without a build step. It lives in its own file
 * for the same reason -- inside a component nothing could reach it, which is
 * how the Trance Gate's S-curve stayed wrong for as long as it did.
 *
 * NEITHER COPY IS COMPARED AGAINST THE OTHER. Both this and the C are pinned
 * to `test/shape_table.txt`, generated by the engine itself. Two identically
 * wrong transcriptions agree with each other perfectly; only the engine's own
 * output settles it. A picture that merely looks plausible is not evidence.
 *
 * Regenerate the fixture with `sc_shape_table`, and only when the curve maths
 * is MEANT to change.
 */

import { shape, CURVES } from '@ultraviolet/ui/curve';

/* The curve itself is the kit's one copy (ui-kit/src/lib/curve.js); this file
 * is what the ducker draws with it. Re-exported, so the test pins the module
 * the drawing uses. */
export { shape, CURVES };

/*
 * THE IDEALISED SINGLE SHOT, WHICH IS WHAT THE EDITOR DRAWS.
 *
 * `duckAt` is the shape one trigger makes when nothing interrupts it: from
 * zero, down to full, and back. That is right for the editor, because the
 * editor is where you say what shape you WANT.
 *
 * IT IS NOT THE ENVELOPE THE ENGINE RUNS, and the difference is deliberate. The
 * engine anchors a retrigger on the level it has actually reached, so a duck
 * that fires again mid-recovery does not retrace this curve -- and no drawing
 * can show that, because it depends on when the next trigger arrives. What the
 * plugin pushes instead is the measured gain, drawn beside this. The line says
 * the intent; the measured trace says what happened.
 *
 * THE PHASE WRAPS, WHICH IS WHAT MAKES A NEGATIVE DELAY DRAWABLE.
 *
 * On the Cycle source, Delay is a position in a PERIODIC cycle rather than a
 * wait -- so -20% is 80%, and the duck that belongs to the next beat is already
 * on screen at the right-hand end of this one. Wrapping is not a drawing trick
 * here; it is what the engine does, which fires on `floor(phase - offset)`.
 *
 * `p.cycle` says which mechanism applies. MIDI and Sidechain have nothing
 * periodic to anticipate, so there Delay is a wait and a negative one is no
 * wait at all -- the same clamp the engine makes.
 *
 * Lengths are PERCENTAGES OF THE CYCLE, the unit the engine stores them in, and
 * `t` is in the same unit. Depth is not applied: this returns the attenuation
 * 0..1, and what a depth does with it is one multiply where the drawing happens.
 */

/** Any phase into 0..100. */
const wrap = (v) => ((v % 100) + 100) % 100;

/** Where the duck begins, as a phase in 0..100. */
function startOf(p) {
  const d = p.delay ?? 0;
  return p.cycle ? wrap(d) : Math.max(0, d);
}

export function duckAt(p, t) {
  const a = Math.max(0, p.attack ?? 0);
  const h = Math.max(0, p.hold ?? 0);
  const r = Math.max(0, p.release ?? 0);
  const curve = p.curve | 0;

  /* Elapsed since the trigger. On Cycle this wraps, so the part of the envelope
   * that belongs to the next beat is drawn at this one's right-hand end. */
  const e = p.cycle ? wrap(t - startOf(p)) : t - startOf(p);
  if (!(e >= 0)) return 0; /* NaN included */

  if (e < a) return shape(curve, a > 0 ? e / a : 1);
  if (e < a + h) return 1;
  if (e < a + h + r) return 1 - shape(curve, (e - a - h) / r);
  return 0;
}

/**
 * Where each stage boundary sits, as a phase in 0..100 -- the handles are these
 * and the axis' landmark is one of them, so there is one arithmetic for both.
 *
 * `span` is the UNWRAPPED total, which is what says whether the shape can
 * finish inside a cycle at all. Wrapping it would hide exactly the case the
 * overrun mark exists to report.
 */
export function bounds(p) {
  const a = Math.max(0, p.attack ?? 0);
  const h = Math.max(0, p.hold ?? 0);
  const r = Math.max(0, p.release ?? 0);
  const s = startOf(p);
  const at = (v) => (p.cycle ? wrap(v) : v);
  return {
    start: at(s),
    bottom: at(s + a),
    holdEnd: at(s + a + h),
    end: at(s + a + h + r),
    span: a + h + r,
  };
}
