// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Torben Gräber

/*
 * Listen-In's wire format, and the table both sides are pinned to.
 *
 * THE ORACLE ARRANGEMENT, third time. The curves had shape() twice -- once in
 * the engine, once in JavaScript -- and the S-curve's first half was
 * un-mirrored in the copy for as long as both existed, because a wrong curve
 * is still a curve. The columns had the same shape and the same fix.
 *
 * So there is ONE table, generated by the C++ the plugin actually calls, and
 * two tests that neither generate it nor compare against each other:
 *
 *   listenin_wire      Wire.cpp still agrees with ui/test/wire_table.txt
 *   listenin_wire_js   ui/src/lib/state.js still agrees with the same file
 *
 * Regenerate with `listenin_wire --dump > ui/test/wire_table.txt`, and only
 * when the format is MEANT to change -- which means the decoder changes in the
 * same commit.
 */
#define DOCTEST_CONFIG_IMPLEMENT
#include "doctest.h"

#include "Wire.h"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <string>
#include <vector>

using namespace listenin::wire;

struct Case { int slot; int status; float peak; };

/*
 * THE CASES THE TABLE PINS, chosen rather than exhaustive. Every one is a
 * boundary the JavaScript on the other side can land wrong on, and not one of
 * them is visible in a window that looks fine.
 */
static std::vector<Case> table_cases()
{
  return {
    {1, kIdle, 0.f},           /* the quiet end, and the first slot        */
    {16, kLive, 1.f},          /* the loud end, and the last slot          */
    {3, kLive, 0.5f},
    {3, kTaken, 0.f},
    {7, kUnavailable, 0.25f},
    /* ROUNDING AT THE FOURTH DECIMAL. "%.4f" of 0.00005 is "0.0001" on one
     * rounding mode and "0.0000" on another; a decoder that assumed either
     * would be right about this repository and wrong about somebody's. */
    {2, kLive, 0.00005f},
    {2, kLive, 0.99995f},
    /* A VALUE ABOVE FULL SCALE, which a host really can hand us. It is clamped
     * here rather than in the editor, so that every reader of this format gets
     * the same answer rather than each one deciding. */
    {4, kLive, 1.7f},
    {5, kLive, -0.3f},         /* and below zero, likewise                 */
  };
}

/*
 * EACH LINE CARRIES THE STRING *AND* WHAT IT MEANS:
 *
 *     <encoded>\t<slot>\t<status>\t<peak>
 *
 * The first draft dumped only the encoded string, and the JavaScript half
 * "verified" it by splitting that string on ':' and checking the pieces
 * against themselves. It passed against a table with a deliberately corrupted
 * value in it, because a self-consistent line decodes self-consistently. The
 * test was vacuous and looked exactly like the Spectrogram's, which is not.
 *
 * The Spectrogram's table works because it holds INPUT bytes beside EXPECTED
 * output. This one now does the same: the C++ states what a correct decoder
 * must produce, and the JavaScript is checked against that rather than against
 * its own arithmetic.
 */
static void dump()
{
  for (const Case& c : table_cases())
  {
    const std::string enc = encode_state(c.slot, c.status, c.peak);
    /* The peak AS THE STRING CARRIES IT -- clamped and rounded to four
     * decimals -- because that is what a decoder can possibly recover. */
    const double shown = std::atof(enc.substr(enc.rfind(':') + 1).c_str());
    std::printf("%s\t%d\t%d\t%.4f\n", enc.c_str(), c.slot, c.status, shown);
  }
}

TEST_CASE("the state string is the format the editor parses")
{
  CHECK(encode_state(3, kLive, 0.5f) == "3:1:0.5000");
  CHECK(encode_state(1, kIdle, 0.f) == "1:0:0.0000");
  CHECK(encode_state(16, kUnavailable, 1.f) == "16:3:1.0000");
}

TEST_CASE("peak is clamped rather than passed through")
{
  /* A bar drawn past the end of its well is a drawing bug, not information. */
  CHECK(encode_state(1, kLive, 2.5f) == "1:1:1.0000");
  CHECK(encode_state(1, kLive, -1.f) == "1:1:0.0000");
}

TEST_CASE("slots are clamped into the range that exists")
{
  CHECK(clamp_slot(0) == 1);
  CHECK(clamp_slot(-5) == 1);
  CHECK(clamp_slot(1) == 1);
  CHECK(clamp_slot(16) == 16);
  CHECK(clamp_slot(17) == 16);
  /* A project written by a future version with more slots must open, on a slot
   * that exists, rather than assert. */
  CHECK(clamp_slot(99) == 16);
}

TEST_CASE("a label loses what would break the message and keeps the rest")
{
  char out[32];

  parse_label("Bass", out, sizeof(out));
  CHECK(std::string(out) == "Bass");

  /* A colon would split a message that is parsed by position; a newline would
   * end it. Both are dropped rather than escaped -- there is nothing a person
   * means by typing one into a name field. */
  parse_label("Ba:ss", out, sizeof(out));
  CHECK(std::string(out) == "Bass");
  parse_label("Ba\nss\tx", out, sizeof(out));
  CHECK(std::string(out) == "Bassx");

  parse_label(nullptr, out, sizeof(out));
  CHECK(std::string(out) == "");
  parse_label("", out, sizeof(out));
  CHECK(std::string(out) == "");
}

/*
 * THE TRUNCATION CASE, which is the reason parse_label exists at all.
 *
 * The first version walked back over continuation bytes and then dropped the
 * lead byte unconditionally. That is right for a sequence that was cut and
 * WRONG FOR EVERY COMPLETE ONE: "Bä" is 42 C3 A4, and it came back as "B".
 * The common case was the broken one, which is exactly the kind of bug that
 * ships.
 */
TEST_CASE("a complete multi-byte name survives untouched")
{
  char out[32];
  parse_label("B\xC3\xA4sse", out, sizeof(out));       /* Bässe */
  CHECK(std::string(out) == "B\xC3\xA4sse");

  parse_label("\xE2\x99\xAF", out, sizeof(out));       /* a sharp sign, 3 bytes */
  CHECK(std::string(out) == "\xE2\x99\xAF");

  parse_label("\xF0\x9F\x8E\x9B", out, sizeof(out));   /* a slider, 4 bytes */
  CHECK(std::string(out) == "\xF0\x9F\x8E\x9B");
}

TEST_CASE("a name cut at the limit never ends mid-character")
{
  /*
   * A string cut in the middle of a UTF-8 sequence is not a rendering glitch:
   * the editor's TextDecoder refuses it, so the WHOLE message is lost and the
   * window silently stops updating.
   *
   * Seven 2-byte characters is 14 bytes; a cap of 14 leaves room for 13 plus a
   * NUL, which lands inside the seventh.
   */
  char out[14];
  parse_label("\xC3\xA4\xC3\xA4\xC3\xA4\xC3\xA4\xC3\xA4\xC3\xA4\xC3\xA4", out, sizeof(out));
  CHECK(std::strlen(out) == 12);              /* six whole characters */
  CHECK((unsigned char) out[11] == 0xA4);     /* ending on a complete one */

  /* Every prefix length, against every sequence width: whatever the cap, the
   * result is always valid UTF-8 -- never a trailing partial sequence. */
  const char* src = "a\xC3\xA4\xE2\x99\xAF\xF0\x9F\x8E\x9Bz";
  for (int cap = 1; cap <= 16; cap++)
  {
    char buf[32];
    const int n = parse_label(src, buf, cap);
    REQUIRE(n < cap);
    int i = 0;
    while (i < n)
    {
      const unsigned char c = (unsigned char) buf[i];
      int need = (c & 0x80) == 0x00 ? 1
               : (c & 0xE0) == 0xC0 ? 2
               : (c & 0xF0) == 0xE0 ? 3
               : (c & 0xF8) == 0xF0 ? 4 : -1;
      REQUIRE(need > 0);
      REQUIRE(i + need <= n);
      i += need;
    }
    CHECK(i == n);
  }
}

int main(int argc, char** argv)
{
  for (int i = 1; i < argc; i++)
  {
    if (std::strcmp(argv[i], "--dump") == 0) { dump(); return 0; }

    if (std::strcmp(argv[i], "--verify") == 0 && i + 1 < argc)
    {
      /* The table is the oracle for the JavaScript too, so this half checks
       * that the C++ still produces exactly what was recorded. */
      std::FILE* f = std::fopen(argv[i + 1], "r");
      if (f == nullptr) { std::printf("cannot open %s\n", argv[i + 1]); return 1; }

      int bad = 0, n = 0;
      char line[256];
      for (const Case& c : table_cases())
      {
        if (std::fgets(line, sizeof(line), f) == nullptr) { bad++; break; }
        std::string row(line);
        while (!row.empty() && (row.back() == '\n' || row.back() == '\r'))
          row.pop_back();
        /* Only the first column is this half's business; the rest is what the
         * JavaScript is pinned to. */
        const std::string want = row.substr(0, row.find('\t'));
        const std::string got = encode_state(c.slot, c.status, c.peak);
        if (got != want)
        {
          std::printf("line %d: table says \"%s\", Wire.cpp says \"%s\"\n",
                      n + 1, want.c_str(), got.c_str());
          bad++;
        }
        n++;
      }
      std::fclose(f);
      if (bad) { std::printf("FAILED: %d mismatches\n", bad); return 1; }
      std::printf("ok: %d lines agree with Wire.cpp\n", n);
      /* And the assertions above still have to pass. */
    }
  }

  doctest::Context ctx(argc, argv);
  return ctx.run();
}
