/*
 * The Spectrogram's wire format, and the table both sides are pinned to.
 * Copyright (c) 2026 Torben Gräber. MIT -- see LICENSE.
 *
 * WHY A TABLE AND NOT A SECOND IMPLEMENTATION.
 *
 * The editor's decoder was checked against an encoder written inside its own
 * test file, and that file said so:
 *
 *   "See OnIdle in Spectrogram.cpp -- this is a transcription of it, which is
 *    the point: if the two disagree, this test is the disagreement."
 *
 * A transcription agrees with its source right up until somebody edits one of
 * them. That is exactly the arrangement shape() had -- once in the engine,
 * once in JavaScript -- and the S-curve's first half was un-mirrored in the
 * JavaScript copy for as long as both existed, because a wrong curve is still
 * a curve and a shifted spectrogram is still a spectrogram.
 *
 * So there is one table, generated by the C++ that the plugin actually calls,
 * and two tests that neither generate nor compare against each other:
 *
 *   spectro_wire        Wire.cpp still agrees with ui/test/wire_table.txt
 *   spectro_columns_js  ui/src/lib/columns.js still agrees with the same file
 *
 * Regenerate with `spectro_wire --dump > ui/test/wire_table.txt`, and only
 * when the wire format is MEANT to change -- which means the editor's decoder
 * changes in the same commit.
 */
#define DOCTEST_CONFIG_IMPLEMENT
#include "doctest.h"

#include "Wire.h"

#include <cstdio>
#include <cstring>
#include <string>
#include <vector>

using namespace spectro::wire;

/*
 * THE CASES THE TABLE PINS, chosen rather than exhaustive.
 *
 * Every one of them is a boundary the hand-written nibble map on the other
 * side can land wrong on, and none of them is visible in a picture.
 */
static std::vector<std::vector<unsigned char>> table_cases()
{
  std::vector<std::vector<unsigned char>> cases;

  /* 9 -> A is char code 57 -> 65, with six characters in between that are
   * neither. A decoder that subtracts '0' throughout is correct for exactly
   * the first ten values and plausible for the rest. */
  std::vector<unsigned char> all256(256);
  for (int i = 0; i < 256; i++) all256[size_t(i)] = (unsigned char) i;
  cases.push_back(all256);

  /* The ends, and the two values either side of the nibble boundary. */
  cases.push_back({0, 1, 15, 16, 127, 128, 254, 255});

  /* Silence: every byte the floor. A decoder that drops leading zeros turns
   * this into a short payload and the batch is rejected whole. */
  cases.push_back({0, 0, 0, 0, 0, 0, 0, 0});

  /* Full scale throughout, the other end of the same mistake. */
  cases.push_back({255, 255, 255, 255});

  /* One band, which is the degenerate column the axis code also has to hold. */
  cases.push_back({42});

  return cases;
}

/*
 * THE LINE FORMAT, and why it carries the bytes twice.
 *
 *     <cols> <bands> <b,b,b,...> <encoded>
 *
 * The decimals are the INPUT and the last field is what this encoder made of
 * it. Each side of the wire checks itself against the table and neither is
 * given the other's answer:
 *
 *   spectro_wire        encoding the decimals produces that payload
 *   spectro_columns_js  decoding that payload produces those decimals
 *
 * Without the decimals the editor's test could only decode the payload and
 * compare it against itself, which passes for any self-consistent decoder --
 * including one that is wrong in the same direction as the encoder.
 */
static void emit_case(FILE* out, const unsigned char* data, int cols, int bands)
{
  fprintf(out, "%d %d ", cols, bands);
  for (int i = 0; i < cols * bands; i++)
    fprintf(out, "%s%d", i ? "," : "", int(data[i]));
  fprintf(out, " %s\n", encode_columns(data, cols, bands).c_str());
}

static void dump_table(FILE* out)
{
  for (const auto& c : table_cases())
    emit_case(out, c.data(), 1, int(c.size()));

  /* Multi-column batches, where the column-major order is what can be wrong.
   * A row-major decoder produces a transposed picture, which still looks like
   * a spectrogram. */
  const unsigned char two[8] = {1, 2, 3, 4, 250, 251, 252, 253};
  emit_case(out, two, 2, 4);

  const unsigned char three[9] = {0, 128, 255, 255, 0, 128, 128, 255, 0};
  emit_case(out, three, 3, 3);
}

static int verify_table(const char* path)
{
  FILE* ref = fopen(path, "r");
  if (!ref)
  {
    printf("  cannot open %s\n", path);
    return 1;
  }

  /* Generate into memory and compare line for line, so a disagreement names
   * the line rather than handing over two files to diff by eye. */
  char tmp[1 << 17];
  FILE* mem = fmemopen(tmp, sizeof tmp, "w");
  dump_table(mem);
  fclose(mem);

  int line = 0, bad = 0;
  char want[1 << 15], got[1 << 15];
  char* cursor = tmp;

  while (fgets(want, sizeof want, ref))
  {
    char* nl = strchr(cursor, '\n');
    const size_t len = nl ? size_t(nl - cursor) + 1 : strlen(cursor);
    if (len == 0 || len >= sizeof got)
    {
      printf("  TABLE SHORT at line %d\n", line + 1);
      fclose(ref);
      return 1;
    }
    memcpy(got, cursor, len);
    got[len] = '\0';
    cursor += len;
    line++;

    if (strcmp(want, got) != 0 && ++bad <= 5)
    {
      /* NAME THE POSITION, not the two lines. A 256-band case is 600
       * characters wide and the drift that matters -- a nibble, a swapped
       * column -- is one character somewhere inside it. Two truncated lines
       * printed above each other look identical and teach the reader to stop
       * looking, which is the failure mode this whole file exists to avoid. */
      int at = 0;
      while (want[at] && got[at] && want[at] == got[at]) at++;

      const int from = at > 12 ? at - 12 : 0;

      /* Windowed and newline-free: these are fragments of a line, and a stray
       * '\n' from fgets would break the two apart on screen. */
      char w[29] = {0}, g[29] = {0};
      strncpy(w, want + from, 28);
      strncpy(g, got + from, 28);
      for (char* q = w; *q; q++) if (*q == '\n') *q = ' ';
      for (char* q = g; *q; q++) if (*q == '\n') *q = ' ';

      printf("  WIRE FORMAT CHANGED at line %d, character %d\n", line, at + 1);
      printf("    want ...%s\n", w);
      printf("    got  ...%s\n", g);
    }
  }

  fclose(ref);

  if (bad)
  {
    printf("  %d of %d lines differ.\n", bad, line);
    printf("  If that was intended, regenerate the fixture AND check\n");
    printf("  ui/src/lib/columns.js still matches it.\n");
    return 1;
  }

  printf("  %d cases, encoded by the plugin's own Wire.cpp, match the table    ok\n",
         line);
  return 0;
}

/* ------------------------------------------------------------------ claims */

TEST_CASE("the header names the batch's shape")
{
  const unsigned char c[6] = {1, 2, 3, 4, 5, 6};
  CHECK(encode_columns(c, 2, 3).substr(0, 4) == "2:3:");
  CHECK(encode_columns(c, 3, 2).substr(0, 4) == "3:2:");
}

TEST_CASE("every byte value survives the nibble table")
{
  std::vector<unsigned char> all(256);
  for (int i = 0; i < 256; i++) all[size_t(i)] = (unsigned char) i;

  const std::string s = encode_columns(all.data(), 1, 256);
  const std::string body = s.substr(s.find_last_of(':') + 1);

  REQUIRE(body.size() == 512);
  for (int i = 0; i < 256; i++)
  {
    const std::string pair = body.substr(size_t(i) * 2, 2);
    CHECK(std::stoi(pair, nullptr, 16) == i);
  }
}

TEST_CASE("the hex is upper case, because the decoder's nibble map assumes it")
{
  const unsigned char c[3] = {0xAB, 0xCD, 0xEF};
  const std::string s = encode_columns(c, 1, 3);
  CHECK(s == "1:3:ABCDEF");
}

TEST_CASE("columns are laid out one after another, not interleaved")
{
  /* Two columns of three bands. Transposed, this reads 04 15 26 -- a picture
   * rotated by 90 degrees, which at a glance is still a spectrogram. */
  const unsigned char c[6] = {0, 1, 2, 4, 5, 6};
  CHECK(encode_columns(c, 2, 3) == "2:3:000102040506");
}

TEST_CASE("a batch with nothing in it encodes to nothing at all")
{
  /* Not "0:0:", which the decoder would have to special-case. The caller
   * checks cols > 0 before sending, and this is the belt for that. */
  const unsigned char c[1] = {0};
  CHECK(encode_columns(c, 0, 8).empty());
  CHECK(encode_columns(c, 4, 0).empty());
  CHECK(encode_columns(nullptr, 4, 8).empty());
}

TEST_CASE("the axis is comma separated with no trailing comma")
{
  const float hz[3] = {20.6f, 41.2f, 82.4f};
  CHECK(encode_axis(hz, 3) == "20.6,41.2,82.4");
}

TEST_CASE("the axis keeps one decimal, which is past what a label shows")
{
  /* Values chosen off the rounding boundary on purpose. 19999.95f is stored
   * as 19999.949..., so it prints 19999.9 and an expectation of 20000.0 is
   * the TEST being wrong about floats rather than the encoder being wrong
   * about the axis -- which is worth a line here, because writing that
   * expectation is the obvious first mistake. */
  const float hz[3] = {20.64f, 20.66f, 20000.0f};
  const std::string s = encode_axis(hz, 3);
  CHECK(s == "20.6,20.7,20000.0");
}

TEST_CASE("an empty axis is empty rather than a lone separator")
{
  const float hz[1] = {440.f};
  CHECK(encode_axis(hz, 0).empty());
  CHECK(encode_axis(nullptr, 3).empty());
}

TEST_CASE("a range without a colon is refused and changes neither end")
{
  float lo = 111.f, hi = 222.f;
  CHECK(parse_range("nonsense", lo, hi) == false);
  CHECK(lo == 111.f);
  CHECK(hi == 222.f);
}

TEST_CASE("a range splits at the colon")
{
  float lo = 0.f, hi = 0.f;
  REQUIRE(parse_range("2000:16000", lo, hi));
  CHECK(lo == doctest::Approx(2000.f));
  CHECK(hi == doctest::Approx(16000.f));
}

/* ------------------------------------------------------------------- sync */

TEST_CASE("the sync message carries the clock in the order the editor reads it")
{
  const std::string s = encode_sync(8.5, 120.0, 4, 4, true, 0.017);
  CHECK(s == "8.500000:120.0000:4:4:1:0.01700000");

  /* The running flag is the fifth field and is 0/1, not "true"/"false" -- the
   * editor tests it against the character. */
  CHECK(encode_sync(0.0, 120.0, 4, 4, false, 0.017).find(":0:") != std::string::npos);
}

TEST_CASE("the position keeps enough decimals to separate two columns")
{
  /* At 200 BPM a column is ~0.06 beats. Three decimals would land two adjacent
   * columns on the same number and stack them on one pixel. */
  const std::string a = encode_sync(100.000000, 200.0, 4, 4, true, 0.0568);
  const std::string b = encode_sync(100.056800, 200.0, 4, 4, true, 0.0568);
  CHECK(a != b);
}

TEST_CASE("a negative position survives the wire")
{
  /* A count-in, or the playhead dragged before the start. The editor folds it
   * back into the window; this file's only job is not to lose the sign. */
  const std::string s = encode_sync(-0.5, 120.0, 4, 4, true, 0.017);
  CHECK(s.compare(0, 2, "-0") == 0);
}

TEST_CASE("an odd time signature survives the wire")
{
  const std::string s = encode_sync(1.0, 90.0, 6, 8, true, 0.02);
  CHECK(s.find(":6:8:") != std::string::npos);
}

/* ----------------------------------------------------------------- beats */

TEST_CASE("beats advance with the samples that carry them")
{
  /* 120 BPM is 2 beats a second, so a second of 48 kHz is 2 beats. */
  CHECK(advance_beats(0.0, 48000, 120.0, 48000.0) == doctest::Approx(2.0));
  CHECK(advance_beats(10.0, 24000, 120.0, 48000.0) == doctest::Approx(11.0));
  /* And it accumulates from wherever it already was, including below zero. */
  CHECK(advance_beats(-1.0, 48000, 120.0, 48000.0) == doctest::Approx(1.0));
}

TEST_CASE("beats refuse to advance on arguments that would poison the position")
{
  /* A NaN here would not be one bad block: the position is carried forward, so
   * it would be every block after it for the life of the session. */
  CHECK(advance_beats(5.0, 512, 120.0, 0.0) == doctest::Approx(5.0));
  CHECK(advance_beats(5.0, 512, 0.0, 48000.0) == doctest::Approx(5.0));
  CHECK(advance_beats(5.0, 512, -120.0, 48000.0) == doctest::Approx(5.0));
  CHECK(advance_beats(5.0, 0, 120.0, 48000.0) == doctest::Approx(5.0));
  CHECK(advance_beats(5.0, -1, 120.0, 48000.0) == doctest::Approx(5.0));
}

TEST_CASE("a full tick's payload fits the transport's cap")
{
  /* The same arithmetic as the static_assert in Spectrogram.h, asserted here
   * too because the header's version is invisible until someone compiles the
   * plugin -- and this suite does not. */
  CHECK(framed_size(32 * 256 * 2) < 65536);
}

/* -------------------------------------------------------------------- main */

int main(int argc, char** argv)
{
  /* The repo's convention: one binary both generates and verifies. Usage goes
   * to stderr, results to stdout, 2 for a usage error and 1 for a mismatch. */
  if (argc > 1 && strcmp(argv[1], "--dump") == 0)
  {
    dump_table(stdout);
    return 0;
  }

  if (argc > 1 && strcmp(argv[1], "--verify") == 0)
  {
    if (argc < 3)
    {
      fprintf(stderr,
              "usage: spectro_wire [--verify table.txt | --dump > table.txt]\n");
      return 2;
    }
    if (verify_table(argv[2]) != 0)
      return 1;
    /* and the claims too -- the table pins the format, these pin the rules */
  }
  else if (argc > 1)
  {
    fprintf(stderr,
            "usage: spectro_wire [--verify table.txt | --dump > table.txt]\n");
    return 2;
  }

  doctest::Context ctx;
  ctx.setOption("no-intro", true);
  ctx.setOption("no-version", true);
  return ctx.run();
}
