/*
 * The readout decoder, against the engine's own fixture.
 * Copyright (c) 2026 Torben Gräber. MIT.
 *
 * readout.js decodes a string only the engine produces, and two editors now
 * depend on that decoding being right: the WebView one and the Max for Live
 * device's grid. Neither can run the engine, so the fixture is generated by
 * the engine itself (tests/ui_readout.c) and the decoder is checked against
 * THAT -- the same arrangement curves.test.mjs has with shape_table.txt, and
 * for the same reason. A decoder checked against its author's belief about
 * the format agrees with any misunderstanding in it.
 *
 * THE EXPECTATIONS BELOW ARE DERIVED BY HAND, not by calling the decoder.
 * 0xBEEF's bits are written out because a test that computed them the way
 * readout.js does would pass with readout.js reading the hex backwards --
 * which is the single most likely bug in the file, and the reason the fixture
 * includes a 13-step pattern where that mistake stops being invisible.
 *
 *   node --test ui/test/readout.test.mjs
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { parseReadout, hexToBits } from
  '../../../trance-gate/ui/src/lib/readout.js';

const here = dirname(fileURLToPath(import.meta.url));
const TABLE = process.env.TG_READOUT_TABLE ?? join(here, 'readout_table.txt');

/* name -> readout string, from the engine-generated fixture. */
const rows = Object.fromEntries(
  readFileSync(TABLE, 'utf8')
    .split('\n')
    .filter((l) => l && !l.startsWith('#'))
    .map((l) => l.split('\t')));

/*
 * 0xBEEF, least significant bit first, written out by hand:
 *
 *     F = 1111 -> steps 0..3
 *     E = 1110 -> steps 4..7
 *     E = 1110 -> steps 8..11
 *     B = 1011 -> steps 12..15
 */
const BEEF_BITS = [
  1, 1, 1, 1,
  0, 1, 1, 1,
  0, 1, 1, 1,
  1, 1, 0, 1,
].map(Boolean);

/* 0x22, the same way: 2 = 0010, so step 1 and step 5 are ties. */
const TIE_BITS = [
  0, 1, 0, 0,
  0, 1, 0, 0,
  0, 0, 0, 0,
  0, 0, 0, 0,
].map(Boolean);

test('a 16-step pattern decodes least-significant-bit first', () => {
  const u = parseReadout(rows.beef16);
  assert.ok(u, 'the fixture row did not decode');
  assert.equal(u.length, 16);
  assert.deepEqual(u.steps, BEEF_BITS);
  assert.deepEqual(u.ties, TIE_BITS);
  assert.equal(u.cursor, 0);
  assert.equal(u.moving, false);
});

/*
 * THE CASE THAT CATCHES A FORWARD READ. With 13 steps the hex no longer
 * fills whole nibbles, so a decoder reading the string left to right lands
 * on a different pattern rather than on the same one shifted -- and a
 * pattern that is merely different still looks like a pattern.
 */
test('a length that is not a multiple of four decodes from the same end', () => {
  const u = parseReadout(rows.beef13);
  assert.ok(u);
  assert.equal(u.length, 13);
  assert.deepEqual(u.steps, BEEF_BITS.slice(0, 13));
  assert.deepEqual(u.ties, TIE_BITS.slice(0, 13));
  assert.equal(u.depths.length, 13, 'depths are truncated to the length too');
});

/*
 * DEPTHS RUN FORWARDS, unlike the bitmaps -- two hex digits per step in step
 * order, because the engine writes them as a run of bytes rather than as a
 * number. Mixing the two conventions up is exactly why both live in one file.
 */
test('per-step depths decode forwards, two hex digits each', () => {
  const u = parseReadout(rows.depths);
  assert.ok(u);
  /* The engine was given 0.05 + 0.06 * step, which it stores as a byte. */
  for (let i = 0; i < 16; i++) {
    const want = Math.round((0.05 + 0.06 * i) * 255) / 255;
    assert.ok(Math.abs(u.depths[i] - want) < 1 / 255 + 1e-9,
      `step ${i}: got ${u.depths[i]}, want about ${want}`);
  }
  /* Ascending, which a backwards read would reverse. */
  for (let i = 1; i < 16; i++)
    assert.ok(u.depths[i] > u.depths[i - 1], `depths must ascend at ${i}`);
  assert.equal(u.cursor, 3);
});

test('an empty pattern decodes as empty rather than as a default', () => {
  const u = parseReadout(rows.empty);
  assert.ok(u);
  assert.deepEqual(u.steps, new Array(16).fill(false));
  assert.deepEqual(u.ties, new Array(16).fill(false));
});

/*
 * A SHORT READ IS NULL, NOT A PARTIAL OBJECT. The caller keeps its last good
 * state; a decoder that filled the gaps would draw a confident empty pattern
 * over a real one, which reads as lost work rather than as a version skew.
 */
test('a string that is not a readout returns null', () => {
  assert.equal(parseReadout('BEEF:22:16'), null);
  assert.equal(parseReadout(''), null);
  assert.equal(parseReadout(undefined), null);
  assert.equal(parseReadout(null), null);
  assert.equal(parseReadout(42), null);
});

test('hexToBits pads and truncates to the length it is asked for', () => {
  assert.deepEqual(hexToBits('F', 2), [true, true]);
  assert.deepEqual(hexToBits('', 3), [false, false, false]);
  assert.deepEqual(hexToBits('1', 5), [true, false, false, false, false]);
});
