/*!
Unit tests for the parts that are pure logic.

WHAT IS TESTED HERE AND WHAT IS NOT. These cover the curve algebra, the stage
machine's bookkeeping, the detector's edge logic and the parameter clamps --
things whose correctness is a property, checkable without a buffer of audio.

The DSP's actual output is pinned elsewhere and deliberately not here: the curve
tables are generated by this engine and checked against it from C and from
JavaScript independently (`tests/sc_shape`, `ui/test/shape.test.mjs`), and the
envelope is MEASURED by driving the real thing with DC rather than transcribed
from the model it is supposed to be verifying.
*/

use crate::follower::Follower;
use crate::midi::{Action, Midi};
use crate::params::{amp_to_db, db_to_amp, Param, PARAM_COUNT};
use crate::shape::{shape, shape_inv, Curve, Env, Stage, Stages};
use crate::{rates, Instance, Source, Transport};

const CURVES: [Curve; 3] = [Curve::Linear, Curve::Exp, Curve::SCurve];

/* ------------------------------------------------------------------ shapes */

#[test]
fn shape_endpoints_and_bounds() {
    for c in CURVES {
        assert_eq!(shape(c, 0.0), 0.0, "{c:?} at 0");
        assert_eq!(shape(c, 1.0), 1.0, "{c:?} at 1");
        /* Out of range and NaN are clamped, not propagated: a NaN gain silences
         * a track permanently and cannot be recovered from. */
        assert_eq!(shape(c, -1.0), 0.0);
        assert_eq!(shape(c, 2.0), 1.0);
        assert_eq!(shape(c, f64::NAN), 0.0);
        for k in 0..=100 {
            let v = shape(c, k as f64 / 100.0);
            assert!((0.0..=1.0).contains(&v), "{c:?} out of range: {v}");
        }
    }
}

#[test]
fn shape_is_monotonic() {
    for c in CURVES {
        let mut prev = -1.0;
        for k in 0..=1000 {
            let v = shape(c, k as f64 / 1000.0);
            assert!(v >= prev, "{c:?} dipped at {k}: {v} < {prev}");
            prev = v;
        }
    }
}

#[test]
fn shape_inv_round_trips() {
    for c in CURVES {
        for k in 1..1000 {
            let t = k as f64 / 1000.0;
            let back = shape_inv(c, shape(c, t));
            assert!((back - t).abs() < 1e-9, "{c:?} t={t} -> {back}");
        }
    }
}

#[test]
fn exponential_is_the_documented_bend() {
    /* Halfway through an exponential stage the envelope is ~82% of the way --
     * the constant the header claims, checked so a change to CURVE_K cannot
     * pass quietly. */
    let v = shape(Curve::Exp, 0.5);
    assert!((v - 0.8176).abs() < 1e-3, "exp at 0.5 = {v}");
}

#[test]
fn scurve_is_flat_at_both_ends_and_antisymmetric() {
    /* The bug this pins: `0.5 * curve_exp(2t)` on both halves leaves the floor
     * vertically, which is the opposite of an S-curve. Compare the slope near
     * the ends against the slope at the middle. */
    let d = 1e-3;
    let ends = shape(Curve::SCurve, d) / d;
    let middle = (shape(Curve::SCurve, 0.5 + d) - shape(Curve::SCurve, 0.5 - d)) / (2.0 * d);
    assert!(ends < 0.5, "S-curve leaves the floor too fast: {ends}");
    assert!(middle > 1.5, "S-curve middle too slow: {middle}");
    assert!(middle > ends * 4.0, "not an S: ends={ends} middle={middle}");

    for k in 0..=500 {
        let t = k as f64 / 1000.0;
        let a = shape(Curve::SCurve, t);
        let b = shape(Curve::SCurve, 1.0 - t);
        assert!((a + b - 1.0).abs() < 1e-12, "not antisymmetric at {t}");
    }
}

/* ----------------------------------------------------------- stage machine */

fn stages(d: f64, a: f64, h: f64, r: f64) -> Stages {
    Stages {
        delay: d,
        attack: a,
        hold: h,
        release: r,
    }
}

/// Run the envelope to completion, returning every emitted value.
fn run(env: &mut Env, s: &Stages, curve: Curve, n: usize, gated: bool) -> Vec<f64> {
    (0..n).map(|_| env.next(curve, s, gated)).collect()
}

#[test]
fn envelope_lasts_exactly_the_sum_of_its_stages() {
    /* The off-by-one this pins: testing a stage's completion AFTER emitting
     * gave len+1 samples per stage, so a nominal 30 ran for 33. */
    for (d, a, h, r) in [
        (0.0, 10.0, 10.0, 10.0),
        (5.0, 20.0, 1.0, 40.0),
        (0.0, 1.0, 0.0, 1.0),
        (7.0, 0.0, 3.0, 0.0),
    ] {
        let s = stages(d, a, h, r);
        let mut env = Env::default();
        env.trigger(1.0, &s);
        let total = (d + a + h + r) as usize;
        let out = run(&mut env, &s, Curve::Linear, total + 4, false);
        assert_eq!(
            env.stage,
            Stage::Idle,
            "{d}/{a}/{h}/{r} not finished after {total}+4"
        );
        /* Idle from exactly `total` onwards, and not before. */
        assert!(
            out[total..].iter().all(|v| *v == 0.0),
            "{d}/{a}/{h}/{r} still ducking past its length: {:?}",
            &out[total..]
        );
        if total > 0 {
            assert!(
                out[..total].iter().any(|v| *v > 0.0),
                "{d}/{a}/{h}/{r} never ducked"
            );
        }
    }
}

#[test]
fn linear_attack_is_a_straight_ramp() {
    let s = stages(0.0, 10.0, 5.0, 5.0);
    let mut env = Env::default();
    env.trigger(1.0, &s);
    let out = run(&mut env, &s, Curve::Linear, 10, false);
    for (i, v) in out.iter().enumerate() {
        let want = i as f64 / 10.0;
        assert!((v - want).abs() < 1e-12, "sample {i}: {v} != {want}");
    }
}

#[test]
fn delay_holds_the_signal_open_before_the_duck() {
    let s = stages(8.0, 4.0, 4.0, 4.0);
    let mut env = Env::default();
    env.trigger(1.0, &s);
    let out = run(&mut env, &s, Curve::Linear, 8, false);
    assert!(
        out.iter().all(|v| *v == 0.0),
        "the delay ducked something: {out:?}"
    );
    assert_eq!(env.stage, Stage::Delay);
    /* And the attack starts on the very next sample. */
    let v = env.next(Curve::Linear, &s, false);
    assert_eq!(v, 0.0, "attack's first sample is t=0");
    assert_eq!(env.stage, Stage::Attack);
}

#[test]
fn a_retrigger_never_steps_the_gain_upwards() {
    /* THE CLICK THIS PREVENTS. Retriggering mid-release with `from` reset to
     * zero would send the gain back to unity for one sample. */
    let s = stages(0.0, 20.0, 5.0, 100.0);
    let mut env = Env::default();
    env.trigger(1.0, &s);
    run(&mut env, &s, Curve::Linear, 40, false); /* into the release */
    assert_eq!(env.stage, Stage::Release);
    let before = env.duck;
    assert!(before > 0.1 && before < 1.0, "not mid-release: {before}");

    env.trigger(1.0, &s);
    let after = env.next(Curve::Linear, &s, false);
    assert!(
        after >= before - 1e-12,
        "gain jumped up on retrigger: {before} -> {after}"
    );
}

#[test]
fn a_release_falls_from_where_the_machine_got_to() {
    /* Release during the attack, so the envelope never reached `scale`.
     * Releasing from the floor would step the gain DOWN when asked to come up. */
    let s = stages(0.0, 100.0, 10.0, 50.0);
    let mut env = Env::default();
    env.trigger(1.0, &s);
    run(&mut env, &s, Curve::Linear, 20, false);
    let at = env.duck;
    assert!(at > 0.0 && at < 0.5, "not early in the attack: {at}");
    env.release(&s);
    let first = env.next(Curve::Linear, &s, false);
    assert!(
        (first - at).abs() < 1e-12,
        "release started from {first}, not {at}"
    );
}

#[test]
fn a_shallow_trigger_ducks_shallowly() {
    let s = stages(0.0, 4.0, 10.0, 4.0);
    let mut env = Env::default();
    env.trigger(0.25, &s);
    let out = run(&mut env, &s, Curve::Linear, 12, false);
    let peak = out.iter().cloned().fold(0.0f64, f64::max);
    assert!((peak - 0.25).abs() < 1e-12, "peak {peak} != scale 0.25");
}

#[test]
fn gate_mode_holds_until_released() {
    let s = stages(0.0, 2.0, 3.0, 4.0);
    let mut env = Env::default();
    env.trigger(1.0, &s);
    /* Far longer than Hold, and it must still be at the floor. */
    let out = run(&mut env, &s, Curve::Linear, 500, true);
    assert_eq!(env.stage, Stage::Hold);
    assert_eq!(*out.last().unwrap(), 1.0);
    env.release(&s);
    /* A release of four samples EMITS four and reaches Idle on the fifth call:
     * `pos` counts samples already emitted, so the stage is finished when the
     * fifth call finds `pos == len`. */
    run(&mut env, &s, Curve::Linear, 4, false);
    assert_eq!(env.stage, Stage::Release, "still releasing on its last sample");
    assert_eq!(env.next(Curve::Linear, &s, false), 0.0);
    assert_eq!(env.stage, Stage::Idle);
}

#[test]
fn every_stage_at_zero_is_a_no_op_not_a_hang() {
    let s = stages(0.0, 0.0, 0.0, 0.0);
    let mut env = Env::default();
    env.trigger(1.0, &s);
    /* The loop's bound is what makes this terminate rather than spin. */
    assert_eq!(env.next(Curve::Linear, &s, false), 0.0);
    assert_eq!(env.stage, Stage::Idle);
}

/* --------------------------------------------------------------- follower */

/// One drum-shaped hit: a fast rise, a decay, then silence.
fn hit(out: &mut Vec<f32>, peak: f32, len: usize, gap: usize) {
    for i in 0..len {
        let e = 1.0 - (i as f32 / len as f32);
        out.push(peak * e * e);
    }
    out.extend(std::iter::repeat(0.0).take(gap));
}

fn count_fires(key: &[f32], threshold: f64, lockout_samples: f64, sr: f64) -> usize {
    let mut f = Follower::new(sr);
    key.iter()
        .filter(|s| f.next(**s, **s, threshold, lockout_samples))
        .count()
}

#[test]
fn one_hit_is_one_trigger() {
    /* THE FAULT THIS PINS: a bare `|x| > threshold` fires on every sample the
     * waveform spends above the line -- dozens per hit. */
    let sr = 48000.0;
    let mut key = Vec::new();
    for _ in 0..4 {
        hit(&mut key, 0.9, 480, 9600);
    }
    assert_eq!(count_fires(&key, db_to_amp(-24.0), 0.0, sr), 4);
}

#[test]
fn the_lockout_absorbs_a_second_hit_inside_its_window() {
    /* THE DIVISION OF LABOUR THIS PINS. Two hits 100 ms apart are two humps as
     * far as the detector is concerned -- that is what the 25 ms fall buys --
     * so whether they are one trigger or two is the Lockout's decision and
     * nothing else's. A longer fall would answer it first and silently. */
    let sr = 48000.0;
    let mut key = Vec::new();
    hit(&mut key, 0.9, 240, 4560); /* 100 ms between the two onsets */
    hit(&mut key, 0.9, 240, 9600);
    let th = db_to_amp(-24.0);
    assert_eq!(count_fires(&key, th, 0.0, sr), 2, "no lockout: both fire");
    /* 150 ms of lockout is 7200 samples, which spans the second onset. */
    assert_eq!(count_fires(&key, th, 7200.0, sr), 1, "lockout should absorb it");
}

#[test]
fn the_detector_recovers_between_hits_on_its_own() {
    /* The guard on FALL_MS: if the fall grows past one waveform cycle it starts
     * merging hits the user asked to keep apart, and the Lockout stops working.
     * At 100 ms of separation the detector must come back under the line by
     * itself. */
    let sr = 48000.0;
    let mut key = Vec::new();
    for _ in 0..6 {
        hit(&mut key, 0.9, 240, 4560);
    }
    assert_eq!(count_fires(&key, db_to_amp(-24.0), 0.0, sr), 6);
}

#[test]
fn the_threshold_is_a_threshold() {
    let sr = 48000.0;
    let mut quiet = Vec::new();
    hit(&mut quiet, 0.02, 480, 4800); /* about -34 dB peak */
    assert_eq!(count_fires(&quiet, db_to_amp(-24.0), 0.0, sr), 0);
    assert_eq!(count_fires(&quiet, db_to_amp(-50.0), 0.0, sr), 1);
}

#[test]
fn the_detector_reads_the_louder_channel_not_their_mean() {
    /* A kick panned hard left halves in a sum and can fall under a threshold
     * set while it was centred -- the threshold would be reading the panner. */
    let mut f = Follower::new(48000.0);
    let th = db_to_amp(-12.0);
    let mut fired = false;
    for _ in 0..480 {
        if f.next(0.9, 0.0, th, 0.0) {
            fired = true;
        }
    }
    assert!(fired, "a hard-panned hit must still trigger");
}

#[test]
fn a_nan_in_the_key_does_not_latch_the_detector() {
    /* A NaN env compares false against everything, so `above` would latch and
     * the detector would never fire again for the life of the session. */
    let mut f = Follower::new(48000.0);
    let th = db_to_amp(-24.0);
    for _ in 0..64 {
        f.next(f32::NAN, f32::INFINITY, th, 0.0);
    }
    let mut fired = false;
    for _ in 0..480 {
        if f.next(0.9, 0.9, th, 0.0) {
            fired = true;
        }
    }
    assert!(fired, "the detector is stuck after a NaN");
}

/* ------------------------------------------------------------------- midi */

fn note_on(ch: u8, note: u8, vel: u8) -> [u8; 3] {
    [0x90 | (ch - 1), note, vel]
}
fn note_off(ch: u8, note: u8) -> [u8; 3] {
    [0x80 | (ch - 1), note, 0]
}

#[test]
fn midi_filters_channel_and_note() {
    let mut m = Midi {
        channel: 2,
        note: 36,
        ..Default::default()
    };
    assert!(m.decode(&note_on(1, 36, 100)).is_none(), "wrong channel");
    assert!(m.decode(&note_on(2, 37, 100)).is_none(), "wrong note");
    assert!(matches!(
        m.decode(&note_on(2, 36, 100)),
        Some(Action::Trigger(_))
    ));

    /* Omni takes every channel. */
    let mut omni = Midi {
        channel: 0,
        note: 36,
        ..Default::default()
    };
    for ch in 1..=16 {
        assert!(matches!(
            omni.decode(&note_on(ch, 36, 100)),
            Some(Action::Trigger(_))
        ));
    }
}

#[test]
fn a_note_on_at_velocity_zero_is_a_note_off() {
    /* Hosts and hardware both send it. Read as a trigger at zero depth it
     * leaves Gate mode holding a note that was never pressed. */
    let mut m = Midi {
        gate: true,
        ..Default::default()
    };
    assert!(matches!(
        m.decode(&note_on(1, 36, 100)),
        Some(Action::Trigger(_))
    ));
    assert_eq!(m.held, 1);
    assert_eq!(m.decode(&note_on(1, 36, 0)), Some(Action::Release));
    assert_eq!(m.held, 0);
}

#[test]
fn gate_mode_releases_only_on_the_last_note_off() {
    let mut m = Midi {
        gate: true,
        ..Default::default()
    };
    m.decode(&note_on(1, 36, 100));
    m.decode(&note_on(1, 36, 100));
    assert_eq!(m.held, 2);
    assert_eq!(m.decode(&note_off(1, 36)), None, "one note still down");
    assert_eq!(m.decode(&note_off(1, 36)), Some(Action::Release));
}

#[test]
fn trigger_mode_ignores_note_offs() {
    let mut m = Midi::default();
    m.decode(&note_on(1, 36, 100));
    assert_eq!(m.decode(&note_off(1, 36)), None);
}

#[test]
fn velocity_scales_depth_only_when_asked_to() {
    let mut m = Midi {
        vel_sens: 0.0,
        ..Default::default()
    };
    assert_eq!(m.decode(&note_on(1, 36, 1)), Some(Action::Trigger(1.0)));

    m.vel_sens = 1.0;
    let Some(Action::Trigger(s)) = m.decode(&note_on(1, 36, 64)) else {
        panic!("no trigger")
    };
    assert!((s - 64.0 / 127.0).abs() < 1e-12, "scale {s}");
    let Some(Action::Trigger(s)) = m.decode(&note_on(1, 36, 127)) else {
        panic!("no trigger")
    };
    assert!((s - 1.0).abs() < 1e-12);
}

#[test]
fn a_panic_resets_whatever_the_note_filter_says() {
    /* A panic that only arrived on the trigger note would not be a panic. */
    for cc in [120u8, 123u8] {
        let mut m = Midi {
            note: 36,
            gate: true,
            ..Default::default()
        };
        m.decode(&note_on(1, 36, 100));
        assert_eq!(m.held, 1);
        assert_eq!(m.decode(&[0xB0, cc, 0]), Some(Action::Reset), "CC {cc}");
        assert_eq!(m.held, 0);
    }
}

#[test]
fn a_short_message_is_rejected_not_indexed_into() {
    let mut m = Midi::default();
    assert!(m.decode(&[]).is_none());
    assert!(m.decode(&[0x90]).is_none());
    assert!(m.decode(&[0x90, 36]).is_none());
}

/* ----------------------------------------------------------- parameters */

#[test]
fn db_and_amp_round_trip() {
    for db in [-59.0, -48.0, -24.0, -12.0, -6.0, -0.5, 0.0] {
        let back = amp_to_db(db_to_amp(db));
        assert!((back - db).abs() < 1e-9, "{db} -> {back}");
    }
    /* The bottom of the range means "anything triggers", so it is zero
     * amplitude rather than -60 dB of it. */
    assert_eq!(db_to_amp(-60.0), 0.0);
    /* And the inverse floors rather than returning -inf, so no readout can
     * ever print "-inf dB". */
    assert_eq!(amp_to_db(0.0), -60.0);
    assert_eq!(amp_to_db(-1.0), -60.0);
}

#[test]
fn every_parameter_round_trips_through_set_num_and_num() {
    let mut p = Instance::new(48000.0);
    /* A value inside each range that is not the default, so a setter that
     * silently does nothing is caught. */
    let cases: [(Param, f64); 15] = [
        (Param::Source, 2.0),
        (Param::Rate, 6.0),
        (Param::TimeMode, 1.0),
        (Param::Delay, 12.5),
        (Param::Attack, 3.25),
        (Param::Hold, 44.0),
        (Param::Release, 111.5),
        (Param::Depth, 0.625),
        (Param::Curve, 2.0),
        (Param::Channel, 7.0),
        (Param::Note, 60.0),
        (Param::MidiMode, 1.0),
        (Param::VelSens, 0.5),
        (Param::Threshold, -18.0),
        (Param::Lockout, 33.0),
    ];
    for (param, v) in cases {
        p.set_num(param, v);
        let back = p.num(param);
        assert!(
            (back - v).abs() < 1e-9,
            "{}: set {v}, read {back}",
            param.key()
        );
    }
}

#[test]
fn every_parameter_round_trips_through_the_string_door() {
    /* The string door must agree with the numeric one, because a Schwung shell
     * and a host automation lane are two views of one state. */
    let mut a = Instance::new(48000.0);
    let mut b = Instance::new(48000.0);
    let cases: [(Param, f64); 15] = [
        (Param::Source, 1.0),
        (Param::Rate, 2.0),
        (Param::TimeMode, 1.0),
        (Param::Delay, 5.5),
        (Param::Attack, 7.75),
        (Param::Hold, 20.0),
        (Param::Release, 90.0),
        (Param::Depth, 0.8),
        (Param::Curve, 2.0),
        (Param::Channel, 0.0),
        (Param::Note, 48.0),
        (Param::MidiMode, 0.0),
        (Param::VelSens, 0.25),
        (Param::Threshold, -30.0),
        (Param::Lockout, 10.0),
    ];
    let mut buf = [0u8; 256];
    for (param, v) in cases {
        a.set_num(param, v);
        let n = a.get_param(param.key(), &mut buf);
        assert!(n > 0, "{} has no readout", param.key());
        let text = std::str::from_utf8(&buf[..n as usize]).unwrap().to_owned();
        assert!(
            b.set_param(param.key(), &text),
            "{} not accepted by the string door",
            param.key()
        );
        let back = b.num(param);
        assert!(
            (back - v).abs() < 1e-6,
            "{}: {v} -> \"{text}\" -> {back}",
            param.key()
        );
    }
}

#[test]
fn the_string_door_takes_a_label_as_well_as_an_index() {
    let mut p = Instance::new(48000.0);
    p.set_param("rate", "1/8");
    assert_eq!(rates::RATES[p.num(Param::Rate) as usize].label, "1/8");
    p.set_param("curve", "S-Curve");
    assert_eq!(p.num(Param::Curve), Curve::SCurve as i32 as f64);
    p.set_param("source", "Sidechain");
    assert_eq!(p.num(Param::Source), Source::Sidechain as i32 as f64);
    p.set_param("midi_mode", "Gate");
    assert_eq!(p.num(Param::MidiMode), 1.0);
    p.set_param("channel", "Omni");
    assert_eq!(p.num(Param::Channel), 0.0);
}

#[test]
fn out_of_range_is_clamped_and_nan_is_dropped() {
    let mut p = Instance::new(48000.0);
    p.set_num(Param::Depth, 5.0);
    assert_eq!(p.num(Param::Depth), 1.0);
    p.set_num(Param::Depth, -5.0);
    assert_eq!(p.num(Param::Depth), 0.0);

    p.set_num(Param::Attack, 12.0);
    /* A NaN from a host is not a value, and clamping would propagate it. */
    p.set_num(Param::Attack, f64::NAN);
    assert_eq!(p.num(Param::Attack), 12.0, "a NaN overwrote a good value");

    p.set_num(Param::Attack, 9_999.0);
    assert_eq!(p.num(Param::Attack), crate::STAGE_MAX_PCT);
    p.set_num(Param::Delay, 9_999.0);
    assert_eq!(p.num(Param::Delay), crate::DELAY_RANGE_PCT);
}

#[test]
fn an_unknown_key_is_refused_by_both_doors() {
    let mut p = Instance::new(48000.0);
    assert!(!p.set_param("wobble", "1"));
    let mut buf = [0u8; 64];
    assert_eq!(p.get_param("wobble", &mut buf), -1);
    assert!(Param::from_i32(PARAM_COUNT).is_none());
    assert!(Param::from_i32(-1).is_none());
}

#[test]
fn changing_the_curve_mid_duck_does_not_move_the_gain() {
    /* THE CLICK THIS PREVENTS: swapping the curve and leaving `pos` alone jumps
     * the level to wherever the new curve is at that time. */
    for (from, to) in [
        (Curve::Linear, Curve::Exp),
        (Curve::Exp, Curve::SCurve),
        (Curve::SCurve, Curve::Linear),
    ] {
        for stage_under_test in [Stage::Attack, Stage::Release] {
            let mut p = Instance::new(48000.0);
            p.set_num(Param::Curve, from as i32 as f64);
            p.set_num(Param::Source, Source::Midi as i32 as f64);
            /* The stage lengths are PERCENTAGES OF THE CYCLE, and the cycle
             * here is a 1/4 at 120 bpm and 48 kHz -- 24 000 samples. So 5% is
             * 1200 samples of attack, 1% is 240 of hold, and 20% is 4800 of
             * release. Reading these as milliseconds is what made the first
             * version of this test run 3000 samples into a 24 000-sample
             * attack and then assert it was in the release. */
            p.set_num(Param::Attack, 5.0);
            p.set_num(Param::Hold, 1.0);
            p.set_num(Param::Release, 20.0);

            let mut buf = vec![0.0f32; 8192];
            p.on_midi(&note_on(1, 36, 127), 0);
            let n = if stage_under_test == Stage::Attack {
                600 /* half way up the 1200-sample attack */
            } else {
                1600 /* past attack + hold, into the release */
            };
            p.process_f32(&mut buf[..n * 2], n, None);
            assert_eq!(p.stage(), stage_under_test, "{from:?}->{to:?} setup");

            let before = p.duck_now();
            p.set_num(Param::Curve, to as i32 as f64);
            /* The level is a state, not a computation: the curve change must
             * not touch it at all. */
            assert_eq!(
                p.duck_now(),
                before,
                "{from:?} -> {to:?} in {stage_under_test:?} moved the gain"
            );
            /* And the next sample must continue from there, not jump. */
            p.process_f32(&mut buf[..2], 1, None);
            let after = p.duck_now();
            assert!(
                (after - before).abs() < 0.05,
                "{from:?} -> {to:?} in {stage_under_test:?}: {before} -> {after}"
            );
        }
    }
}

/* ------------------------------------------------------- the whole engine */

/// Drive `frames` of silence-shaped audio with a transport advancing as a host
/// would, in blocks, and report how many triggers fired.
fn run_transport(p: &mut Instance, bpm: f64, sr: f64, blocks: usize, frames: usize) -> u32 {
    let start = p.fires();
    let mut buf = vec![0.0f32; frames * 2];
    let samples_per_beat = 60.0 / bpm * sr;
    let mut beats = 0.0;
    for _ in 0..blocks {
        let t = Transport {
            running: true,
            beats,
            bpm: bpm as f32,
        };
        p.process_f32(&mut buf, frames, Some(&t));
        beats += frames as f64 / samples_per_beat;
    }
    p.fires().wrapping_sub(start)
}

#[test]
fn the_cycle_fires_once_per_division() {
    let sr = 48000.0;
    /* 120 bpm, 1/4 -> one cycle per beat -> 24000 samples. 100 blocks of 480
     * is exactly two beats, so exactly two triggers. */
    let mut p = Instance::new(sr);
    p.set_param("rate", "1/4");
    assert_eq!(run_transport(&mut p, 120.0, sr, 100, 480), 2);

    /* 1/8 doubles it. */
    let mut p = Instance::new(sr);
    p.set_param("rate", "1/8");
    assert_eq!(run_transport(&mut p, 120.0, sr, 100, 480), 4);
}

#[test]
fn a_stopped_transport_opens_the_cycle_but_not_the_other_sources() {
    let sr = 48000.0;
    let mut buf = vec![1.0f32; 512];

    /* Cycle: stopped means open, and open means untouched. */
    let mut p = Instance::new(sr);
    p.set_param("depth", "1");
    p.process_f32(&mut buf, 256, None);
    assert!(buf.iter().all(|v| *v == 1.0), "a stopped cycle ducked");

    /* MIDI: a duck must still work with the timeline parked -- which is most
     * of how anyone auditions one. */
    let mut p = Instance::new(sr);
    p.set_param("source", "MIDI");
    p.set_param("depth", "1");
    p.set_param("attack", "0");
    p.on_midi(&note_on(1, 36, 127), 0);
    let mut buf = vec![1.0f32; 512];
    p.process_f32(&mut buf, 256, None);
    assert!(
        buf.iter().any(|v| *v < 0.5),
        "a MIDI duck did nothing with the transport stopped"
    );
}

#[test]
fn a_midi_event_lands_on_its_own_sample_not_the_block_boundary() {
    /* The jitter this removes: `ducker.c` applies a note at the top of the
     * block it arrived in, up to 5 ms early or late at a 256-frame buffer. */
    let sr = 48000.0;
    let mut p = Instance::new(sr);
    p.set_param("source", "MIDI");
    p.set_param("depth", "1");
    p.set_param("attack", "0");
    p.set_param("hold", "50");
    let at = 100;
    p.on_midi(&note_on(1, 36, 127), at);
    let mut buf = vec![1.0f32; 512];
    p.process_f32(&mut buf, 256, None);
    for i in 0..at {
        assert_eq!(buf[i * 2], 1.0, "ducked early at sample {i}");
    }
    assert!(buf[at * 2] < 1.0, "did not duck at sample {at}");
}

#[test]
fn an_offset_past_the_end_of_the_block_is_late_not_lost() {
    let sr = 48000.0;
    let mut p = Instance::new(sr);
    p.set_param("source", "MIDI");
    p.set_param("depth", "1");
    p.set_param("attack", "0");
    p.set_param("hold", "50");
    /* A host reporting an offset against a different buffer size is a real
     * thing, and the queue is cleared per block -- so an unclamped offset is
     * an event that never happens. */
    p.on_midi(&note_on(1, 36, 127), 9_999);
    let mut buf = vec![1.0f32; 128];
    p.process_f32(&mut buf, 64, None);
    assert!(buf[126] < 1.0, "the event was dropped rather than clamped");
}

#[test]
fn depth_zero_is_a_bit_exact_bypass() {
    /* No special case in the code: the product collapses to exactly 1.0 and
     * multiplying by exactly 1.0 is the identity in IEEE 754. This is the test
     * that says so out loud. */
    let sr = 48000.0;
    let mut p = Instance::new(sr);
    p.set_param("depth", "0");
    p.set_param("source", "MIDI");
    p.on_midi(&note_on(1, 36, 127), 0);

    let input: Vec<f32> = (0..512)
        .map(|i| ((i as f32) * 0.017).sin() * 0.7 + 1e-30)
        .collect();
    let mut buf = input.clone();
    p.process_f32(&mut buf, 256, None);
    assert_eq!(buf, input, "depth 0 changed a sample");
}

#[test]
fn the_sidechain_only_listens_when_it_is_the_source() {
    let sr = 48000.0;
    let mut key = Vec::new();
    hit(&mut key, 0.9, 240, 240);
    let silence = vec![0.0f32; key.len()];

    /* As the source, a key hit ducks. */
    let mut p = Instance::new(sr);
    p.set_param("source", "Sidechain");
    p.set_param("depth", "1");
    p.set_param("attack", "0");
    p.set_param("hold", "80");
    p.push_key(&key, &key, key.len());
    let mut buf = vec![1.0f32; key.len() * 2];
    p.process_f32(&mut buf, key.len(), None);
    assert!(buf.iter().any(|v| *v < 0.5), "the key did not trigger");

    /* On Cycle, the same key is ignored entirely. */
    let mut p = Instance::new(sr);
    p.set_param("source", "Cycle");
    p.set_param("depth", "1");
    p.push_key(&key, &key, key.len());
    let mut buf = vec![1.0f32; key.len() * 2];
    p.process_f32(&mut buf, key.len(), None);
    assert!(
        buf.iter().all(|v| *v == 1.0),
        "a stopped cycle ducked on the sidechain"
    );
    let _ = silence;
}

#[test]
fn switching_source_abandons_the_old_one() {
    /* A held MIDI note must not keep a cycle duck open, and the detector must
     * not fire on a stale edge when the source comes back. */
    let sr = 48000.0;
    let mut p = Instance::new(sr);
    p.set_param("source", "MIDI");
    p.set_param("midi_mode", "Gate");
    p.set_param("depth", "1");
    p.set_param("attack", "0");
    p.on_midi(&note_on(1, 36, 127), 0);
    let mut buf = vec![1.0f32; 256];
    p.process_f32(&mut buf, 128, None);
    assert_eq!(p.stage(), Stage::Hold, "gate did not hold");

    p.set_param("source", "Cycle");
    assert_eq!(p.stage(), Stage::Idle, "the held note survived the switch");
}

#[test]
fn the_three_buffer_formats_agree() {
    /* ONE GAIN LAW, THREE FORMATS -- and this is what stops it drifting into
     * three. The i16 path is the Move's, the split path is the plugin's. */
    let sr = 48000.0;
    let n = 2048;
    let mk = |src: Source| {
        let mut p = Instance::new(sr);
        p.set_num(Param::Source, src as i32 as f64);
        p.set_param("attack", "5");
        p.set_param("hold", "10");
        p.set_param("release", "60");
        p
    };

    let mut a = mk(Source::Midi);
    let mut b = mk(Source::Midi);
    let mut c = mk(Source::Midi);
    a.on_midi(&note_on(1, 36, 127), 0);
    b.on_midi(&note_on(1, 36, 127), 0);
    c.on_midi(&note_on(1, 36, 127), 0);

    let dc = 0.5f32;
    let mut inter = vec![dc; n * 2];
    let mut l = vec![dc; n];
    let mut r = vec![dc; n];
    let mut i16buf = vec![(dc * 16384.0) as i16; n * 2];

    a.process_f32(&mut inter, n, None);
    b.process_f32_split(&mut l, &mut r, n, None);
    c.process_i16(&mut i16buf, n, None);

    for i in 0..n {
        assert_eq!(inter[i * 2], l[i], "interleaved vs split at {i}");
        assert_eq!(inter[i * 2 + 1], r[i], "interleaved vs split at {i}");
        /* The i16 path quantises, so compare within one LSB of 16384. */
        let want = l[i] * 16384.0;
        assert!(
            (i16buf[i * 2] as f32 - want).abs() <= 1.0,
            "i16 at {i}: {} vs {want}",
            i16buf[i * 2]
        );
    }
}

#[test]
fn the_i16_path_clamps_asymmetrically_like_i16_does() {
    /* -32768 is representable and +32768 is not. A symmetric clamp wraps the
     * negative peak of a full-scale signal to +32767. */
    let mut p = Instance::new(48000.0);
    p.set_param("depth", "0"); /* pure pass-through, so only the clamp acts */
    let mut buf = vec![i16::MIN, i16::MAX, i16::MIN, i16::MAX];
    p.process_i16(&mut buf, 2, None);
    assert_eq!(buf, vec![i16::MIN, i16::MAX, i16::MIN, i16::MAX]);
}

#[test]
fn the_ui_readout_has_the_shape_the_editor_parses() {
    let mut p = Instance::new(48000.0);
    let mut buf = [0u8; 512];
    let n = p.get_param("ui", &mut buf);
    assert!(n > 0);
    let text = std::str::from_utf8(&buf[..n as usize]).unwrap();
    let fields: Vec<&str> = text.split(':').collect();
    assert_eq!(
        fields.len(),
        11,
        "the `ui` readout is a positional contract with App.jsx: {text}"
    );
    for f in &fields {
        assert!(!f.is_empty(), "empty field in {text}");
    }

    /* `params` carries exactly one value per parameter, in Param order. */
    let n = p.get_param("params", &mut buf);
    let text = std::str::from_utf8(&buf[..n as usize]).unwrap();
    assert_eq!(text.split(':').count(), PARAM_COUNT as usize, "{text}");
}

#[test]
fn a_sample_rate_change_does_not_leave_a_stage_running_at_the_wrong_speed() {
    let mut p = Instance::new(48000.0);
    p.set_param("source", "MIDI");
    p.set_param("attack", "100");
    p.on_midi(&note_on(1, 36, 127), 0);
    let mut buf = vec![1.0f32; 256];
    p.process_f32(&mut buf, 128, None);
    assert_eq!(p.stage(), Stage::Attack);
    p.set_sample_rate(96000.0);
    assert_eq!(p.stage(), Stage::Idle, "the stage survived a rate change");
    assert_eq!(p.sample_rate(), 96000.0);
}

#[test]
fn the_sweep_is_one_axis_for_all_three_sources() {
    /* WHAT THIS PROTECTS. The editor draws the shape across one cycle and the
     * scope lays the audio on the same axis, so a dip sits under the curve that
     * made it. If `sweep01` disagreed with the trigger instant, the two wells
     * would be two pictures that happen to be stacked. */
    let sr = 48000.0;

    /* Cycle: the sweep IS the transport phase, so it starts at a trigger. */
    let mut p = Instance::new(sr);
    p.set_param("rate", "1/4");
    let mut buf = vec![0.0f32; 1024];
    let t = Transport { running: true, beats: 0.0, bpm: 120.0 };
    p.process_f32(&mut buf, 512, Some(&t));
    assert!(p.sweep01() < 0.05, "cycle sweep did not start at the trigger: {}", p.sweep01());

    /* MIDI: no transport at all, and the sweep still restarts on the note. */
    let mut p = Instance::new(sr);
    p.set_param("source", "MIDI");
    let mut buf = vec![0.0f32; 4096];
    p.process_f32(&mut buf, 2048, None);
    assert_eq!(p.sweep01(), 1.0, "an untriggered sweep must park at the right edge");
    p.on_midi(&note_on(1, 36, 127), 0);
    p.process_f32(&mut buf, 512, None);
    let after = p.sweep01();
    assert!(after > 0.0 && after < 0.1, "midi sweep after 512 of 24000: {after}");

    /* And it SATURATES rather than wraps: a source that has not fired again
     * must not draw a second dip that never happened. */
    for _ in 0..20 {
        p.process_f32(&mut buf, 2048, None);
    }
    assert_eq!(p.sweep01(), 1.0, "the sweep wrapped instead of parking");
}

/* ------------------------------------------------------- the early duck --- */

/// Render with a running transport and report the sample index of every
/// downward edge -- where the gain leaves 1.0.
fn duck_starts(p: &mut Instance, sr: f64, bpm: f64, frames: usize) -> Vec<usize> {
    const BLOCK: usize = 128;
    let mut buf = vec![1.0f32; BLOCK * 2];
    let samples_per_beat = 60.0 / bpm * sr;
    let mut out = Vec::new();
    let mut prev = 1.0f32;
    for off in (0..frames).step_by(BLOCK) {
        for v in buf.iter_mut() {
            *v = 1.0;
        }
        let t = Transport {
            running: true,
            beats: off as f64 / samples_per_beat,
            bpm: bpm as f32,
        };
        p.process_f32(&mut buf, BLOCK, Some(&t));
        for i in 0..BLOCK {
            let g = buf[i * 2];
            if prev >= 1.0 && g < 1.0 {
                out.push(off + i);
            }
            prev = g;
        }
    }
    out
}

fn early_test_instance(sr: f64, delay: f64) -> Instance {
    let mut p = Instance::new(sr);
    p.set_param("rate", "1/4");
    p.set_num(Param::Depth, 1.0);
    p.set_num(Param::Attack, 0.0); /* a step, so the edge is exact */
    p.set_num(Param::Hold, 5.0);
    p.set_num(Param::Release, 5.0);
    p.set_num(Param::Delay, delay);
    p
}

#[test]
fn a_negative_delay_ducks_before_the_beat() {
    /*
     * THE WHOLE POINT OF THE SIGN. At 120 bpm and 1/4 the cycle is 24 000
     * samples, so a quarter of it is 6 000. A delay of +25% puts the duck 6 000
     * samples AFTER the beat; -25% puts it 6 000 samples BEFORE the next one,
     * which is 18 000 after this one.
     *
     * Anticipating an event is impossible; this is not that. The cycle is
     * PERIODIC, so "early" is a position already passed.
     */
    let sr = 48000.0;

    let mut late = early_test_instance(sr, 25.0);
    let late_edges = duck_starts(&mut late, sr, 120.0, 48000);

    let mut early = early_test_instance(sr, -25.0);
    let early_edges = duck_starts(&mut early, sr, 120.0, 48000);

    /*
     * THE FIRST EDGE IS THE FIRST REAL DUCK, and that is worth saying out loud
     * because it was not always. Starting the transport mid-cycle used to fire
     * immediately AND again at the real trigger -- two ducks where the music
     * has one. The transport here starts at beat 0, which is a quarter of a
     * cycle from either trigger point, so a spurious start would show up as an
     * edge at 0.
     */
    assert!(late_edges.len() >= 2, "late: {late_edges:?}");
    assert!(early_edges.len() >= 2, "early: {early_edges:?}");
    assert!(late_edges[0] > 100, "a duck fired on the transport start: {late_edges:?}");
    assert!(early_edges[0] > 100, "a duck fired on the transport start: {early_edges:?}");

    /* Two samples of slack: `inc` is 1/24000, which is not exact in binary, so
     * accumulating it 6000 times lands a sample either side. */
    let near = |got: usize, want: usize| (got as i64 - want as i64).abs() <= 2;
    assert!(near(late_edges[0], 6000), "+25% should duck at 6000: {late_edges:?}");
    assert!(near(early_edges[0], 18000), "-25% should duck at 18000: {early_edges:?}");

    /* And both still fire once per cycle -- the offset moves the duck, it does
     * not add or drop one. */
    assert_eq!(late_edges.len(), early_edges.len(), "{late_edges:?} {early_edges:?}");
}

#[test]
fn zero_delay_ducks_on_the_beat() {
    let sr = 48000.0;
    let mut p = early_test_instance(sr, 0.0);
    let edges = duck_starts(&mut p, sr, 120.0, 48000);
    assert!(!edges.is_empty(), "{edges:?}");
    let near = |got: usize, want: usize| (got as i64 - want as i64).abs() <= 2;
    /* Beat 0 IS a trigger point, so pressing play on it must duck -- which is
     * the case the arrival rule has to keep working while it stops the
     * spurious mid-cycle one. */
    assert!(near(edges[0], 0), "play on the downbeat should duck: {edges:?}");
    assert!(near(edges[1], 24000), "and again a cycle later: {edges:?}");
}

#[test]
fn moving_the_delay_does_not_fire_an_extra_duck() {
    /*
     * FORWARD CROSSINGS ONLY, and this is the fault it prevents. The trigger
     * test is `floor(phase - offset)`, so changing the offset moves the index
     * under the phase -- and a DECREMENT would read as a crossing. Dragging the
     * Delay knob would then put an extra duck in the bar for every pixel.
     */
    let sr = 48000.0;
    const BLOCK: usize = 128;
    let mut p = early_test_instance(sr, 0.0);
    let mut buf = vec![1.0f32; BLOCK * 2];
    let samples_per_beat = 60.0 / 120.0 * sr;

    let before = p.fires();
    /* Sweep the delay across its whole range inside ONE cycle, which is what a
     * drag does. A cycle is 24 000 samples; this covers 12 800 of them. */
    for (k, off) in (0..100).map(|k| (k, k * BLOCK)) {
        p.set_num(Param::Delay, -100.0 + (k as f64) * 2.0);
        for v in buf.iter_mut() {
            *v = 1.0;
        }
        let t = Transport {
            running: true,
            beats: off as f64 / samples_per_beat,
            bpm: 120.0,
        };
        p.process_f32(&mut buf, BLOCK, Some(&t));
    }
    let fired = p.fires() - before;
    /* Half a cycle of audio: the transport start, and at most one boundary the
     * sweep legitimately moved past. Anything more is the knob firing ducks. */
    assert!(fired <= 2, "a delay sweep fired {fired} ducks");
}

#[test]
fn a_negative_delay_is_ignored_where_it_cannot_work() {
    /*
     * MIDI HAS NOTHING PERIODIC TO ANTICIPATE. A note that has not arrived
     * cannot be ducked ahead of, so a negative delay is clamped to no wait
     * rather than refused -- an automation lane is allowed to sweep through it.
     */
    let sr = 48000.0;
    let mut p = Instance::new(sr);
    p.set_param("source", "MIDI");
    p.set_num(Param::Depth, 1.0);
    p.set_num(Param::Attack, 0.0);
    p.set_num(Param::Hold, 20.0);
    p.set_num(Param::Delay, -50.0);
    assert_eq!(p.num(Param::Delay), -50.0, "the value is kept, not refused");

    p.on_midi(&note_on(1, 36, 127), 0);
    let mut buf = vec![1.0f32; 512];
    p.process_f32(&mut buf, 256, None);
    /* No wait: the duck is there on the trigger sample itself. */
    assert!(buf[0] < 1.0, "a negative delay delayed a MIDI duck");
}
