/*!
Whole-engine tests, and the helpers the per-module tests share.

WHERE THE REST LIVE. Each module carries its own tests beside it --
`shape/tests.rs` (the curve algebra and the stage machine), `follower/tests.rs`
(the detector's edge logic), `midi/tests.rs` (what a note means) and
`params/tests.rs` (the clamps and both doors). What is here drives the real
`Instance` through a transport, a MIDI queue or a key buffer, because those are
properties of the parts together rather than of any one of them.

The DSP's actual output is pinned elsewhere and deliberately not here: the curve
tables are generated by this engine and checked against it from C and from
JavaScript independently (`tests/sc_shape`, `ui/test/shape.test.mjs`), and the
envelope is MEASURED by driving the real thing with DC rather than transcribed
from the model it is supposed to be verifying.
*/

use crate::params::{Param, PARAM_COUNT};
use crate::shape::{Curve, Stage};
use crate::{Instance, Source, Transport};

/// Every curve, for the property tests that must hold for each of them.
pub(crate) const CURVES: [Curve; 3] = [Curve::Linear, Curve::Exp, Curve::SCurve];

pub(crate) fn note_on(ch: u8, note: u8, vel: u8) -> [u8; 3] {
    [0x90 | (ch - 1), note, vel]
}
/// One drum-shaped hit: a fast rise, a decay, then silence.
pub(crate) fn hit(out: &mut Vec<f32>, peak: f32, len: usize, gap: usize) {
    for i in 0..len {
        let e = 1.0 - (i as f32 / len as f32);
        out.push(peak * e * e);
    }
    out.extend(std::iter::repeat(0.0).take(gap));
}

pub(crate) fn note_off(ch: u8, note: u8) -> [u8; 3] {
    [0x80 | (ch - 1), note, 0]
}

/* ------------------------------------------------------- the whole engine */

/// Drive `frames` of silence-shaped audio with a transport advancing as a host
/// would, in blocks, and report how many triggers fired.
fn run_transport(p: &mut Instance, bpm: f64, sr: f64, blocks: usize, frames: usize) -> u32 {
    let start = p.fires();
    let mut buf = vec![0.0f32; frames * 2];
    let samples_per_beat = 60.0 / bpm * sr;
    let mut beats = 0.0;
    for _ in 0..blocks {
        let t = Transport {
            running: true,
            beats,
            bpm: bpm as f32,
        };
        p.process_f32(&mut buf, frames, Some(&t));
        beats += frames as f64 / samples_per_beat;
    }
    p.fires().wrapping_sub(start)
}

#[test]
fn the_cycle_fires_once_per_division() {
    let sr = 48000.0;
    /* 120 bpm, 1/4 -> one cycle per beat -> 24000 samples. 100 blocks of 480
     * is exactly two beats, so exactly two triggers. */
    let mut p = Instance::new(sr);
    p.set_param("rate", "1/4");
    assert_eq!(run_transport(&mut p, 120.0, sr, 100, 480), 2);

    /* 1/8 doubles it. */
    let mut p = Instance::new(sr);
    p.set_param("rate", "1/8");
    assert_eq!(run_transport(&mut p, 120.0, sr, 100, 480), 4);
}

#[test]
fn a_stopped_transport_opens_the_cycle_but_not_the_other_sources() {
    let sr = 48000.0;
    let mut buf = vec![1.0f32; 512];

    /* Cycle: stopped means open, and open means untouched. */
    let mut p = Instance::new(sr);
    p.set_param("depth", "1");
    p.process_f32(&mut buf, 256, None);
    assert!(buf.iter().all(|v| *v == 1.0), "a stopped cycle ducked");

    /* MIDI: a duck must still work with the timeline parked -- which is most
     * of how anyone auditions one. */
    let mut p = Instance::new(sr);
    p.set_param("source", "MIDI");
    p.set_param("depth", "1");
    p.set_param("attack", "0");
    p.on_midi(&note_on(1, 36, 127), 0);
    let mut buf = vec![1.0f32; 512];
    p.process_f32(&mut buf, 256, None);
    assert!(
        buf.iter().any(|v| *v < 0.5),
        "a MIDI duck did nothing with the transport stopped"
    );
}

#[test]
fn a_midi_event_lands_on_its_own_sample_not_the_block_boundary() {
    /* The jitter this removes: `ducker.c` applies a note at the top of the
     * block it arrived in, up to 5 ms early or late at a 256-frame buffer. */
    let sr = 48000.0;
    let mut p = Instance::new(sr);
    p.set_param("source", "MIDI");
    p.set_param("depth", "1");
    p.set_param("attack", "0");
    p.set_param("hold", "50");
    let at = 100;
    p.on_midi(&note_on(1, 36, 127), at);
    let mut buf = vec![1.0f32; 512];
    p.process_f32(&mut buf, 256, None);
    for i in 0..at {
        assert_eq!(buf[i * 2], 1.0, "ducked early at sample {i}");
    }
    assert!(buf[at * 2] < 1.0, "did not duck at sample {at}");
}

#[test]
fn an_offset_past_the_end_of_the_block_is_late_not_lost() {
    let sr = 48000.0;
    let mut p = Instance::new(sr);
    p.set_param("source", "MIDI");
    p.set_param("depth", "1");
    p.set_param("attack", "0");
    p.set_param("hold", "50");
    /* A host reporting an offset against a different buffer size is a real
     * thing, and the queue is cleared per block -- so an unclamped offset is
     * an event that never happens. */
    p.on_midi(&note_on(1, 36, 127), 9_999);
    let mut buf = vec![1.0f32; 128];
    p.process_f32(&mut buf, 64, None);
    assert!(buf[126] < 1.0, "the event was dropped rather than clamped");
}

#[test]
fn depth_zero_is_a_bit_exact_bypass() {
    /* No special case in the code: the product collapses to exactly 1.0 and
     * multiplying by exactly 1.0 is the identity in IEEE 754. This is the test
     * that says so out loud. */
    let sr = 48000.0;
    let mut p = Instance::new(sr);
    p.set_param("depth", "0");
    p.set_param("source", "MIDI");
    p.on_midi(&note_on(1, 36, 127), 0);

    let input: Vec<f32> = (0..512)
        .map(|i| ((i as f32) * 0.017).sin() * 0.7 + 1e-30)
        .collect();
    let mut buf = input.clone();
    p.process_f32(&mut buf, 256, None);
    assert_eq!(buf, input, "depth 0 changed a sample");
}

#[test]
fn the_sidechain_only_listens_when_it_is_the_source() {
    let sr = 48000.0;
    let mut key = Vec::new();
    hit(&mut key, 0.9, 240, 240);
    let silence = vec![0.0f32; key.len()];

    /* As the source, a key hit ducks. */
    let mut p = Instance::new(sr);
    p.set_param("source", "Sidechain");
    p.set_param("depth", "1");
    p.set_param("attack", "0");
    p.set_param("hold", "80");
    p.push_key(&key, &key, key.len());
    let mut buf = vec![1.0f32; key.len() * 2];
    p.process_f32(&mut buf, key.len(), None);
    assert!(buf.iter().any(|v| *v < 0.5), "the key did not trigger");

    /* On Cycle, the same key is ignored entirely. */
    let mut p = Instance::new(sr);
    p.set_param("source", "Cycle");
    p.set_param("depth", "1");
    p.push_key(&key, &key, key.len());
    let mut buf = vec![1.0f32; key.len() * 2];
    p.process_f32(&mut buf, key.len(), None);
    assert!(
        buf.iter().all(|v| *v == 1.0),
        "a stopped cycle ducked on the sidechain"
    );
    let _ = silence;
}

#[test]
fn switching_source_abandons_the_old_one() {
    /* A held MIDI note must not keep a cycle duck open, and the detector must
     * not fire on a stale edge when the source comes back. */
    let sr = 48000.0;
    let mut p = Instance::new(sr);
    p.set_param("source", "MIDI");
    p.set_param("midi_mode", "Gate");
    p.set_param("depth", "1");
    p.set_param("attack", "0");
    p.on_midi(&note_on(1, 36, 127), 0);
    let mut buf = vec![1.0f32; 256];
    p.process_f32(&mut buf, 128, None);
    assert_eq!(p.stage(), Stage::Hold, "gate did not hold");

    p.set_param("source", "Cycle");
    assert_eq!(p.stage(), Stage::Idle, "the held note survived the switch");
}

#[test]
fn the_three_buffer_formats_agree() {
    /* ONE GAIN LAW, THREE FORMATS -- and this is what stops it drifting into
     * three. The i16 path is the Move's, the split path is the plugin's. */
    let sr = 48000.0;
    let n = 2048;
    let mk = |src: Source| {
        let mut p = Instance::new(sr);
        p.set_num(Param::Source, src as i32 as f64);
        p.set_param("attack", "5");
        p.set_param("hold", "10");
        p.set_param("release", "60");
        p
    };

    let mut a = mk(Source::Midi);
    let mut b = mk(Source::Midi);
    let mut c = mk(Source::Midi);
    a.on_midi(&note_on(1, 36, 127), 0);
    b.on_midi(&note_on(1, 36, 127), 0);
    c.on_midi(&note_on(1, 36, 127), 0);

    let dc = 0.5f32;
    let mut inter = vec![dc; n * 2];
    let mut l = vec![dc; n];
    let mut r = vec![dc; n];
    let mut i16buf = vec![(dc * 16384.0) as i16; n * 2];

    a.process_f32(&mut inter, n, None);
    b.process_f32_split(&mut l, &mut r, n, None);
    c.process_i16(&mut i16buf, n, None);

    for i in 0..n {
        assert_eq!(inter[i * 2], l[i], "interleaved vs split at {i}");
        assert_eq!(inter[i * 2 + 1], r[i], "interleaved vs split at {i}");
        /* The i16 path quantises, so compare within one LSB of 16384. */
        let want = l[i] * 16384.0;
        assert!(
            (i16buf[i * 2] as f32 - want).abs() <= 1.0,
            "i16 at {i}: {} vs {want}",
            i16buf[i * 2]
        );
    }
}

#[test]
fn the_i16_path_clamps_asymmetrically_like_i16_does() {
    /* -32768 is representable and +32768 is not. A symmetric clamp wraps the
     * negative peak of a full-scale signal to +32767. */
    let mut p = Instance::new(48000.0);
    p.set_param("depth", "0"); /* pure pass-through, so only the clamp acts */
    let mut buf = vec![i16::MIN, i16::MAX, i16::MIN, i16::MAX];
    p.process_i16(&mut buf, 2, None);
    assert_eq!(buf, vec![i16::MIN, i16::MAX, i16::MIN, i16::MAX]);
}

#[test]
fn the_ui_readout_has_the_shape_the_editor_parses() {
    let p = Instance::new(48000.0);
    let mut buf = [0u8; 512];
    let n = p.get_param("ui", &mut buf);
    assert!(n > 0);
    let text = std::str::from_utf8(&buf[..n as usize]).unwrap();
    let fields: Vec<&str> = text.split(':').collect();
    assert_eq!(
        fields.len(),
        11,
        "the `ui` readout is a positional contract with App.jsx: {text}"
    );
    for f in &fields {
        assert!(!f.is_empty(), "empty field in {text}");
    }

    /* `params` carries exactly one value per parameter, in Param order. */
    let n = p.get_param("params", &mut buf);
    let text = std::str::from_utf8(&buf[..n as usize]).unwrap();
    assert_eq!(text.split(':').count(), PARAM_COUNT as usize, "{text}");
}

#[test]
fn a_sample_rate_change_does_not_leave_a_stage_running_at_the_wrong_speed() {
    let mut p = Instance::new(48000.0);
    p.set_param("source", "MIDI");
    p.set_param("attack", "100");
    p.on_midi(&note_on(1, 36, 127), 0);
    let mut buf = vec![1.0f32; 256];
    p.process_f32(&mut buf, 128, None);
    assert_eq!(p.stage(), Stage::Attack);
    p.set_sample_rate(96000.0);
    assert_eq!(p.stage(), Stage::Idle, "the stage survived a rate change");
    assert_eq!(p.sample_rate(), 96000.0);
}

#[test]
fn the_sweep_is_one_axis_for_all_three_sources() {
    /* WHAT THIS PROTECTS. The editor draws the shape across one cycle and the
     * scope lays the audio on the same axis, so a dip sits under the curve that
     * made it. If `sweep01` disagreed with the trigger instant, the two wells
     * would be two pictures that happen to be stacked. */
    let sr = 48000.0;

    /* Cycle: the sweep IS the transport phase, so it starts at a trigger. */
    let mut p = Instance::new(sr);
    p.set_param("rate", "1/4");
    let mut buf = vec![0.0f32; 1024];
    let t = Transport { running: true, beats: 0.0, bpm: 120.0 };
    p.process_f32(&mut buf, 512, Some(&t));
    assert!(p.sweep01() < 0.05, "cycle sweep did not start at the trigger: {}", p.sweep01());

    /* MIDI: no transport at all, and the sweep still restarts on the note. */
    let mut p = Instance::new(sr);
    p.set_param("source", "MIDI");
    let mut buf = vec![0.0f32; 4096];
    p.process_f32(&mut buf, 2048, None);
    assert_eq!(p.sweep01(), 1.0, "an untriggered sweep must park at the right edge");
    p.on_midi(&note_on(1, 36, 127), 0);
    p.process_f32(&mut buf, 512, None);
    let after = p.sweep01();
    assert!(after > 0.0 && after < 0.1, "midi sweep after 512 of 24000: {after}");

    /* And it SATURATES rather than wraps: a source that has not fired again
     * must not draw a second dip that never happened. */
    for _ in 0..20 {
        p.process_f32(&mut buf, 2048, None);
    }
    assert_eq!(p.sweep01(), 1.0, "the sweep wrapped instead of parking");
}

/* ------------------------------------------------------- the early duck --- */

/// Render with a running transport and report the sample index of every
/// downward edge -- where the gain leaves 1.0.
fn duck_starts(p: &mut Instance, sr: f64, bpm: f64, frames: usize) -> Vec<usize> {
    const BLOCK: usize = 128;
    let mut buf = vec![1.0f32; BLOCK * 2];
    let samples_per_beat = 60.0 / bpm * sr;
    let mut out = Vec::new();
    let mut prev = 1.0f32;
    for off in (0..frames).step_by(BLOCK) {
        for v in buf.iter_mut() {
            *v = 1.0;
        }
        let t = Transport {
            running: true,
            beats: off as f64 / samples_per_beat,
            bpm: bpm as f32,
        };
        p.process_f32(&mut buf, BLOCK, Some(&t));
        for i in 0..BLOCK {
            let g = buf[i * 2];
            if prev >= 1.0 && g < 1.0 {
                out.push(off + i);
            }
            prev = g;
        }
    }
    out
}

fn early_test_instance(sr: f64, delay: f64) -> Instance {
    let mut p = Instance::new(sr);
    p.set_param("rate", "1/4");
    p.set_num(Param::Depth, 1.0);
    p.set_num(Param::Attack, 0.0); /* a step, so the edge is exact */
    p.set_num(Param::Hold, 5.0);
    p.set_num(Param::Release, 5.0);
    p.set_num(Param::Delay, delay);
    p
}

#[test]
fn a_negative_delay_ducks_before_the_beat() {
    /*
     * THE WHOLE POINT OF THE SIGN. At 120 bpm and 1/4 the cycle is 24 000
     * samples, so a quarter of it is 6 000. A delay of +25% puts the duck 6 000
     * samples AFTER the beat; -25% puts it 6 000 samples BEFORE the next one,
     * which is 18 000 after this one.
     *
     * Anticipating an event is impossible; this is not that. The cycle is
     * PERIODIC, so "early" is a position already passed.
     */
    let sr = 48000.0;

    let mut late = early_test_instance(sr, 25.0);
    let late_edges = duck_starts(&mut late, sr, 120.0, 48000);

    let mut early = early_test_instance(sr, -25.0);
    let early_edges = duck_starts(&mut early, sr, 120.0, 48000);

    /*
     * THE FIRST EDGE IS THE FIRST REAL DUCK, and that is worth saying out loud
     * because it was not always. Starting the transport mid-cycle used to fire
     * immediately AND again at the real trigger -- two ducks where the music
     * has one. The transport here starts at beat 0, which is a quarter of a
     * cycle from either trigger point, so a spurious start would show up as an
     * edge at 0.
     */
    assert!(late_edges.len() >= 2, "late: {late_edges:?}");
    assert!(early_edges.len() >= 2, "early: {early_edges:?}");
    assert!(late_edges[0] > 100, "a duck fired on the transport start: {late_edges:?}");
    assert!(early_edges[0] > 100, "a duck fired on the transport start: {early_edges:?}");

    /* Two samples of slack: `inc` is 1/24000, which is not exact in binary, so
     * accumulating it 6000 times lands a sample either side. */
    let near = |got: usize, want: usize| (got as i64 - want as i64).abs() <= 2;
    assert!(near(late_edges[0], 6000), "+25% should duck at 6000: {late_edges:?}");
    assert!(near(early_edges[0], 18000), "-25% should duck at 18000: {early_edges:?}");

    /* And both still fire once per cycle -- the offset moves the duck, it does
     * not add or drop one. */
    assert_eq!(late_edges.len(), early_edges.len(), "{late_edges:?} {early_edges:?}");
}

#[test]
fn zero_delay_ducks_on_the_beat() {
    let sr = 48000.0;
    let mut p = early_test_instance(sr, 0.0);
    let edges = duck_starts(&mut p, sr, 120.0, 48000);
    assert!(!edges.is_empty(), "{edges:?}");
    let near = |got: usize, want: usize| (got as i64 - want as i64).abs() <= 2;
    /* Beat 0 IS a trigger point, so pressing play on it must duck -- which is
     * the case the arrival rule has to keep working while it stops the
     * spurious mid-cycle one. */
    assert!(near(edges[0], 0), "play on the downbeat should duck: {edges:?}");
    assert!(near(edges[1], 24000), "and again a cycle later: {edges:?}");
}

#[test]
fn moving_the_delay_does_not_fire_an_extra_duck() {
    /*
     * FORWARD CROSSINGS ONLY, and this is the fault it prevents. The trigger
     * test is `floor(phase - offset)`, so changing the offset moves the index
     * under the phase -- and a DECREMENT would read as a crossing. Dragging the
     * Delay knob would then put an extra duck in the bar for every pixel.
     */
    let sr = 48000.0;
    const BLOCK: usize = 128;
    let mut p = early_test_instance(sr, 0.0);
    let mut buf = vec![1.0f32; BLOCK * 2];
    let samples_per_beat = 60.0 / 120.0 * sr;

    let before = p.fires();
    /* Sweep the delay across its whole range inside ONE cycle, which is what a
     * drag does. A cycle is 24 000 samples; this covers 12 800 of them. */
    for (k, off) in (0..100).map(|k| (k, k * BLOCK)) {
        p.set_num(Param::Delay, -100.0 + (k as f64) * 2.0);
        for v in buf.iter_mut() {
            *v = 1.0;
        }
        let t = Transport {
            running: true,
            beats: off as f64 / samples_per_beat,
            bpm: 120.0,
        };
        p.process_f32(&mut buf, BLOCK, Some(&t));
    }
    let fired = p.fires() - before;
    /* Half a cycle of audio: the transport start, and at most one boundary the
     * sweep legitimately moved past. Anything more is the knob firing ducks. */
    assert!(fired <= 2, "a delay sweep fired {fired} ducks");
}

#[test]
fn a_negative_delay_is_ignored_where_it_cannot_work() {
    /*
     * MIDI HAS NOTHING PERIODIC TO ANTICIPATE. A note that has not arrived
     * cannot be ducked ahead of, so a negative delay is clamped to no wait
     * rather than refused -- an automation lane is allowed to sweep through it.
     */
    let sr = 48000.0;
    let mut p = Instance::new(sr);
    p.set_param("source", "MIDI");
    p.set_num(Param::Depth, 1.0);
    p.set_num(Param::Attack, 0.0);
    p.set_num(Param::Hold, 20.0);
    p.set_num(Param::Delay, -50.0);
    assert_eq!(p.num(Param::Delay), -50.0, "the value is kept, not refused");

    p.on_midi(&note_on(1, 36, 127), 0);
    let mut buf = vec![1.0f32; 512];
    p.process_f32(&mut buf, 256, None);
    /* No wait: the duck is there on the trigger sample itself. */
    assert!(buf[0] < 1.0, "a negative delay delayed a MIDI duck");
}

/* ------------------------------------------------ midi only when it is asked */

#[test]
fn a_note_only_ducks_when_midi_is_the_source() {
    /*
     * THE TRIGGER NOTE IS A MIDI-SOURCE CONTROL. On Cycle or Sidechain a kick
     * pad played on the same track is music passing through, not a request to
     * duck -- and on Cycle it put a second, unsynchronised dip into a pattern
     * that is supposed to be locked to the bar.
     */
    for source in ["Cycle", "Sidechain"] {
        let mut p = Instance::new(48000.0);
        p.set_param("source", source);
        p.set_param("depth", "1");
        p.set_param("attack", "0");
        p.on_midi(&note_on(1, 36, 127), 0);
        let mut buf = vec![1.0f32; 512];
        p.process_f32(&mut buf, 256, None);
        assert!(buf.iter().all(|v| *v == 1.0), "a note ducked the {source} source");
        assert_eq!(p.fires(), 0, "{source} counted a note as a trigger");
    }
}

#[test]
fn a_panic_resets_whatever_the_source() {
    /* CC 120/123 is a host panic, and the v2 vtable has no other door for one:
     * it must open a CYCLE duck too, not only a MIDI one. */
    let sr = 48000.0;
    let mut p = Instance::new(sr);
    p.set_param("attack", "0");
    p.set_param("hold", "100");
    let t = Transport { running: true, beats: 0.0, bpm: 120.0 };
    let mut buf = vec![1.0f32; 256];
    p.process_f32(&mut buf, 128, Some(&t));
    assert!(p.duck_now() > 0.5, "the cycle did not duck");
    p.on_midi(&[0xB0, 123, 0], 0);
    let t = Transport { running: true, beats: 128.0 / sr * 2.0, bpm: 120.0 };
    let mut buf = vec![1.0f32; 256];
    p.process_f32(&mut buf, 128, Some(&t));
    assert_eq!(p.duck_now(), 0.0, "a panic left the cycle ducked");
}

#[test]
fn a_zero_frame_block_changes_nothing() {
    /*
     * THE C ABI REFUSES frames <= 0, THE RUST API DID NOT. An empty block
     * clamped every queued offset "into" a block with no samples and then
     * cleared the queue -- so a note arriving before a zero-length call was
     * never heard -- and the loop's correction divided by the frame count.
     */
    let mut p = Instance::new(48000.0);
    p.set_param("source", "MIDI");
    p.set_param("attack", "0");
    p.on_midi(&note_on(1, 36, 127), 0);
    p.process_f32(&mut [], 0, None);
    let mut buf = vec![1.0f32; 512];
    p.process_f32(&mut buf, 256, None);
    assert!(buf.iter().any(|v| *v < 0.5), "the note was lost to an empty block");

    let mut p = Instance::new(48000.0);
    let t = Transport { running: true, beats: 0.0, bpm: 120.0 };
    let mut buf = vec![1.0f32; 256];
    p.process_f32(&mut buf, 128, Some(&t));
    let before = p.phase01();
    p.process_f32(&mut [], 0, Some(&t));
    assert_eq!(p.phase01(), before);
    assert!(p.phase01().is_finite());
}

#[test]
fn an_instance_is_small_enough_to_build_on_any_stack() {
    /*
     * `Box::new(Instance::new(..))` builds the value on the caller's stack and
     * then moves it -- and on the Move that caller is the audio thread. The two
     * key buffers used to be inline arrays, 64 KB of them, which is a stack
     * frame no realtime thread should be asked for. They live on the heap now,
     * allocated once in `new`, and the instance itself stays small.
     */
    let size = std::mem::size_of::<Instance>();
    assert!(size < 4096, "Instance is {size} bytes");
}

#[test]
fn notes_delivered_out_of_order_each_land_on_their_own_sample() {
    /* A host is not obliged to hand a block's events over sorted. */
    let mut p = Instance::new(48000.0);
    p.set_param("source", "MIDI");
    p.set_param("attack", "0");
    /* 0.5% of a 1/4 cycle at the default 120 bpm is 120 samples: long enough
     * to see, short enough to be over before the second note. */
    p.set_param("hold", "0.5");
    p.set_param("release", "0");
    p.set_param("vel_sens", "1");
    p.on_midi(&note_on(1, 36, 127), 300);
    p.on_midi(&note_on(1, 36, 64), 40);
    let (mut l, mut r) = (vec![1.0f32; 512], vec![1.0f32; 512]);
    let mut gain = vec![0.0f32; 512];
    p.process_f32_split_tap(&mut l, &mut r, Some(&mut gain), None, 512, None);
    assert_eq!(gain[39], 1.0);
    assert!(gain[40] < 1.0 && gain[40] > 0.0, "the soft note, at 40: {}", gain[40]);
    assert_eq!(gain[299], 1.0);
    assert!(gain[300] < gain[40], "the loud note, at 300: {}", gain[300]);
    assert_eq!(p.fires(), 2);
}

/* ------------------------------------------------ gain continuity, measured */

/// Drive a held MIDI duck through `blocks` blocks of `frames`, calling `edit`
/// before each, and return the applied gain per sample.
fn midi_duck(blocks: usize, frames: usize, mut edit: impl FnMut(&mut Instance, usize)) -> Vec<f32> {
    let mut p = Instance::new(48000.0);
    p.set_param("source", "MIDI");
    p.set_param("attack", "20"); /* 4800 samples at 120 bpm, 1/4 */
    p.set_param("hold", "40");
    p.set_param("release", "40");
    p.on_midi(&note_on(1, 36, 127), 0);
    let mut out = Vec::new();
    for b in 0..blocks {
        edit(&mut p, b);
        let (mut l, mut r) = (vec![1.0f32; frames], vec![1.0f32; frames]);
        let mut g = vec![0.0f32; frames];
        p.process_f32_split_tap(&mut l, &mut r, Some(&mut g), None, frames, None);
        out.extend_from_slice(&g);
    }
    out
}

fn max_step(v: &[f32]) -> (f32, usize) {
    let mut worst = (0.0f32, 0);
    for i in 1..v.len() {
        let d = (v[i] - v[i - 1]).abs();
        if d > worst.0 {
            worst = (d, i);
        }
    }
    worst
}

/// A 5 ms glide over a full 0..1 jump moves under 0.005 a sample at 48 kHz,
/// and the duck's own ramps here stay under 0.001.
const STEP_LIMIT: f32 = 0.01;

#[test]
fn moving_depth_mid_duck_does_not_step_the_gain() {
    let g = midi_duck(400, 64, |p, b| {
        if b > 10 && b % 9 == 0 {
            p.set_param("depth", if (b / 9) % 2 == 0 { "0.1" } else { "1" });
        }
    });
    let (d, at) = max_step(&g);
    assert!(d < STEP_LIMIT, "the gain stepped by {d} at sample {at}");
}

#[test]
fn moving_a_stage_length_mid_stage_does_not_step_the_gain() {
    /*
     * A stage's position is a sample COUNT and its length is recomputed every
     * block, so shortening the attack under a running attack used to move
     * `pos / len` past 1 in one block -- the whole rest of the attack in one
     * sample. The position now scales with the length, which keeps the
     * fraction through the stage, and so the level, where it was.
     */
    let g = midi_duck(400, 64, |p, b| {
        let edit = match b {
            30 => Some(("attack", "2")), /* mid-attack, 10x shorter */
            31 => Some(("attack", "20")),
            60 => Some(("attack", "35")),
            140 => Some(("hold", "5")), /* mid-hold */
            240 => Some(("release", "4")), /* mid-release */
            241 => Some(("release", "40")),
            _ => None,
        };
        if let Some((k, v)) = edit {
            p.set_param(k, v);
        }
    });
    let (d, at) = max_step(&g);
    assert!(d < STEP_LIMIT, "the gain stepped by {d} at sample {at}");
}

#[test]
fn a_tempo_change_mid_duck_does_not_step_the_gain() {
    /* The stage lengths are a percentage of the cycle, so a tempo change is
     * a length change -- the same fault through a different door. */
    let mut p = Instance::new(48000.0);
    p.set_param("source", "MIDI");
    p.set_param("attack", "20");
    p.on_midi(&note_on(1, 36, 127), 0);
    let mut g = Vec::new();
    for b in 0..100 {
        let bpm = if b < 30 { 120.0 } else { 60.0 };
        let t = Transport { running: false, beats: -1.0, bpm };
        let (mut l, mut r) = (vec![1.0f32; 64], vec![1.0f32; 64]);
        let mut gb = vec![0.0f32; 64];
        p.process_f32_split_tap(&mut l, &mut r, Some(&mut gb), None, 64, Some(&t));
        g.extend_from_slice(&gb);
    }
    let (d, at) = max_step(&g);
    assert!(d < STEP_LIMIT, "the gain stepped by {d} at sample {at}");
}

/* ------------------------------------------------------ the phase-locked loop */

#[test]
fn the_phase_converges_at_the_same_rate_whatever_the_block_size() {
    /* tg-core's test, for the cycle: the loop's pull is a time constant, so
     * the error left after a given time does not depend on the block size. */
    let sr = 44100.0;
    for frames in [1usize, 32, 128, 4096] {
        let mut p = Instance::new(sr);
        let mut buf = vec![0.5f32; frames * 2];
        let (mut done, mut offset, mut t0) = (0usize, 0.0, None);
        let mut err = 0.0;
        while (done as f64) < 0.4 * sr {
            let t = done as f64 / sr;
            if offset == 0.0 && t >= 0.1 {
                offset = 0.1; /* a tenth of a 1/4 cycle */
                t0 = Some(t);
            }
            let tr = Transport { running: true, beats: t * 2.0 + offset, bpm: 120.0 };
            p.process_f32(&mut buf, frames, Some(&tr));
            done += frames;
            err = done as f64 / sr * 2.0 + offset - p.cycle_pos;
        }
        let dt = done as f64 / sr - t0.unwrap();
        let (got, want) = (err / 0.1, (-dt / crate::TRACK_TAU_S).exp());
        assert!(
            got > 0.0 && (got / want - 1.0).abs() < 0.05,
            "{frames}-frame blocks: {got:.5} of the error left after {dt:.3}s, want {want:.5}"
        );
    }
}

#[test]
fn the_cycle_never_runs_backwards_or_fires_twice() {
    /* A host behind the playhead slows it; it never reverses it, which at a
     * long cycle and a short block used to re-cross the boundary just passed
     * and fire the same duck again. */
    let sr = 44100.0;
    for frames in [1usize, 32, 128, 4096] {
        let mut p = Instance::new(sr);
        p.set_param("rate", "1/1");
        let mut buf = vec![0.5f32; frames * 2];
        let (mut done, mut prev) = (0usize, f64::NEG_INFINITY);
        while done < 2 * 44100 {
            let t = done as f64 / sr;
            /* 0.2 of a 1/1 cycle behind, from half a second in. */
            let lag = if t >= 0.5 { 0.2 * 4.0 } else { 0.0 };
            let tr = Transport { running: true, beats: t * 2.0 - lag, bpm: 120.0 };
            p.process_f32(&mut buf, frames, Some(&tr));
            assert!(p.cycle_pos >= prev, "{frames}-frame blocks: the cycle went back at {t:.4}s");
            prev = p.cycle_pos;
            done += frames;
        }
        /* Two seconds at 120 bpm is exactly one 1/1 cycle: the downbeat fired
         * at the start, and nothing else may have. */
        assert_eq!(p.fires(), 1, "{frames}-frame blocks");
    }
}

/* --------------------------------------------------- transport start and stop */

#[test]
fn stopping_the_transport_releases_a_cycle_duck_instead_of_cutting_it() {
    /*
     * Stopped means open for the Cycle source -- and it used to mean open NOW:
     * `env.reset()` mid-hold stepped the gain from the floor to 1.0 in one
     * sample. The duck now RELEASES, over the release the user set, which is
     * exactly what it would have done had the cycle simply not fired again.
     */
    let sr = 44100.0;
    let mut p = Instance::new(sr);
    p.set_param("attack", "6");
    p.set_param("hold", "40");
    p.set_param("release", "20");
    let mut g = Vec::new();
    let mut beats = 0.0;
    for b in 0..200 {
        let running = !(60..150).contains(&b);
        if !running {
            beats = 0.0;
        }
        let t = Transport { running, beats, bpm: 120.0 };
        let (mut l, mut r) = (vec![1.0f32; 64], vec![1.0f32; 64]);
        let mut gb = vec![0.0f32; 64];
        p.process_f32_split_tap(&mut l, &mut r, Some(&mut gb), None, 64, Some(&t));
        g.extend_from_slice(&gb);
        if running {
            beats += 64.0 / sr * 2.0;
        }
    }
    assert!(g[60 * 64 - 1] < 0.1, "the duck was not at its floor when the transport stopped");
    let (d, at) = max_step(&g);
    assert!(d < STEP_LIMIT, "the gain stepped by {d} at sample {at}");
    /* 20% of a 1/4 cycle at 120 bpm is 4410 samples: open well before the restart. */
    assert!(g[140 * 64..150 * 64].iter().all(|&v| v == 1.0), "not open once stopped");
    assert!(g[150 * 64 + 1400] < 0.1, "the restart did not duck");
}
