// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 Torben Gräber

/*
 * The editor's decoder, against the table the C++ generated.
 *
 * THIS FILE CONTAINS NO ENCODER, and that is the point. The Spectrogram's
 * columns test used to carry a transcription of the plugin's encoder and said
 * so; a transcription agrees with its source until somebody edits one of them,
 * which is how the S-curve stayed wrong in curves.js for as long as both
 * copies existed.
 *
 * So the fixture is generated by the C++ the plugin actually calls
 * (`listenin_wire --dump`), and this side only ever DECODES it.
 */
import { test } from 'node:test';
import assert from 'node:assert/strict';
import { existsSync, readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { decodeState, meterFraction, METER_FLOOR_DB, SLOTS, STATUS_TEXT }
  from '../src/lib/state.js';

const HERE = dirname(fileURLToPath(import.meta.url));
const TABLE = process.env.LISTENIN_WIRE_TABLE || join(HERE, 'wire_table.txt');

/*
 * EACH LINE IS "<encoded>\t<slot>\t<status>\t<peak>" -- the string the plugin
 * sends, and what a correct decoder must get out of it.
 *
 * THE FIRST VERSION OF THIS TEST WAS VACUOUS. The table held only the encoded
 * string, and this side "checked" it by splitting that same string on ':' and
 * comparing the pieces to themselves -- so it passed against a table with a
 * deliberately corrupted value in it. It looked exactly like the Spectrogram's
 * test, which is not vacuous, because THAT table holds input bytes beside
 * expected output. This one does now too.
 */
test('every line the plugin can send decodes to what the C++ says it means', () => {
  assert.ok(existsSync(TABLE),
    `no wire table at ${TABLE} -- regenerate with \`listenin_wire --dump\``);

  const lines = readFileSync(TABLE, 'utf8').split('\n').filter((l) => l.length);
  assert.ok(lines.length >= 9, 'the table is shorter than the cases that made it');

  for (const line of lines) {
    const [encoded, slot, status, peak] = line.split('\t');
    assert.ok(encoded && slot !== undefined && status !== undefined && peak !== undefined,
      `"${line}" is not a four-column row -- regenerate the table`);

    const got = decodeState(encoded);
    assert.ok(got, `"${encoded}" did not decode at all`);

    assert.equal(got.slot, Number(slot), `${encoded}: slot`);
    assert.equal(got.status, Number(status), `${encoded}: status`);
    assert.equal(got.peak, Number(peak), `${encoded}: peak`);

    assert.ok(STATUS_TEXT[got.status], `${encoded}: no text for status ${got.status}`);
  }
});

test('a malformed payload is refused rather than half-read', () => {
  /* The caller keeps what it had, so a dropped frame looks like a dropped
   * frame rather than like a bus that went idle. */
  for (const bad of [
    '', '3', '3:1', '3:1:0.5:9', 'x:1:0.5', '3:x:0.5', '3:1:x',
    '0:1:0.5',        /* slot 0 is not a bus                     */
    '17:1:0.5',       /* nor is one past the end                 */
    '3:9:0.5',        /* no such status                          */
    '3:1:1.5',        /* the C++ clamps, so this never arrives   */
    '3:1:-0.1',
    '3.5:1:0.5',      /* a slot is an integer                    */
    null, undefined, 42,
  ]) {
    assert.equal(decodeState(bad), null, `"${bad}" should not decode`);
  }
});

test('parseInt would have accepted what this rejects', () => {
  /* Number('3x') is NaN; parseInt('3x') is 3. A field that is quietly
   * half-read is worse than one that is refused. */
  assert.equal(decodeState('3x:1:0.5'), null);
  assert.equal(decodeState('3:1x:0.5'), null);
});

test('the meter is linear in dB, not in amplitude', () => {
  /* A linear-amplitude meter spends nine tenths of its length on the top 20 dB
   * and reads as empty for a quiet part that is perfectly audible -- so this
   * window would say "not working" about a bus that is. */
  assert.equal(meterFraction(0), 0);
  assert.equal(meterFraction(1), 1);

  const half = meterFraction(10 ** (METER_FLOOR_DB / 2 / 20)); /* -30 dB */
  assert.ok(Math.abs(half - 0.5) < 1e-9, `-30 dB should be half the well, got ${half}`);

  /* -6 dB is a loud signal and must look like one. On a linear-amplitude bar
   * it would be exactly half. */
  assert.ok(meterFraction(0.5) > 0.85, 'a -6 dB signal reads near the top');

  /* Below the floor, and past the top. */
  assert.equal(meterFraction(10 ** ((METER_FLOOR_DB - 10) / 20)), 0);
  assert.equal(meterFraction(2), 1);
  assert.equal(meterFraction(-1), 0);
});

test('there are sixteen slots and they start at one', () => {
  assert.equal(SLOTS.length, 16);
  assert.equal(SLOTS[0], 1);
  assert.equal(SLOTS[15], 16);
});
