/*
 * The state wire format, decoded. Copyright (c) 2026 Torben Gräber. MIT.
 *
 * PLAIN JAVASCRIPT, NO SOLID, so `node --test` can reach it. This file is
 * pinned to test/wire_table.txt, which is generated by the C++ in Wire.cpp
 * that the plugin actually calls -- neither side is a transcription of the
 * other, which is the arrangement the curves and the columns both arrived at
 * the hard way.
 */

export const STATUS_TEXT = {
  0: 'idle',
  1: 'listening',
  2: 'slot taken',
  3: 'unavailable',
};

/*
 * "<slot>:<status>:<peak>" -- e.g. "3:1:0.4271".
 *
 * A malformed payload returns null rather than a half-filled object: the
 * caller keeps what it had, which is what a dropped frame should look like.
 * Number() rather than parseFloat/parseInt on purpose -- parseInt('3x') is 3,
 * and a field that is quietly half-read is worse than one that is refused.
 */
export function decodeState(text) {
  if (typeof text !== 'string') return null;
  const parts = text.split(':');
  if (parts.length !== 3) return null;

  const slot = Number(parts[0]);
  const status = Number(parts[1]);
  const peak = Number(parts[2]);

  if (!Number.isInteger(slot) || slot < 1 || slot > 16) return null;
  if (!Number.isInteger(status) || status < 0 || status > 3) return null;
  if (!Number.isFinite(peak) || peak < 0 || peak > 1) return null;

  return { slot, status, peak };
}

/* The meter's well is linear in dB, not in amplitude: a linear-amplitude meter
 * spends nine tenths of its length on the top 20 dB and shows nothing at all
 * for a quiet part that is perfectly audible. -60 dB is the floor. */
export const METER_FLOOR_DB = -60;

export function meterFraction(peak) {
  if (!(peak > 0)) return 0;
  const db = 20 * Math.log10(peak);
  if (db <= METER_FLOOR_DB) return 0;
  if (db >= 0) return 1;
  return 1 - db / METER_FLOOR_DB;
}

/* 1..16, for the slot Select. */
export const SLOTS = Array.from({ length: 16 }, (_, i) => i + 1);
